### ISSUE TITLE
Creating New provider defaults to gpt4free despite settings.

### ISSUE THREAD

**Issue by kratosok** [Josh-XT/AGiXT#1038]
### Description

Creating New provider defaults to gpt4free despite settings.

The configuration written to disk appears to be default. 

Also noticed when changing one agent settings it seems to impact the other settings attached to gpt4free. Maybe a ui issue?

`{"commands": {"Write to File": false, "Read File": false, "Search Files": false, "Append to File": false, "Execute Python File": false, "Delete File": false, "Execute Shell": false, "Indent String for Python Code": false, "Generate Commands Dictionary": false, "Use The Search Engine": false, "Get Datetime": false, "Scrape Text with Playwright": false, "Scrape Links with Playwright": false, "Take Screenshot with Playwright": false, "Create Task Chain": false, "Generate Extension from OpenAPI": false, "Generate Agent Helper Chain": false, "Ask for Help or Further Clarification to Complete Task": false, "Create a new command": false, "Execute Python Code": false, "Get Python Code from Response": false, "Get Mindmap for task to break it down": false, "Store information in my long term memory": false, "Research on arXiv": false, "Read GitHub Repository into long term memory": false, "Read Website Content into long term memory": false, "Read non-image file content into long term memory": false, "Get Local Model List": false, "Smart Instruct - No Research": false, "Create New Command": false, "Test_Commands": false, "Generate Smart Task Chain without Research": false, "Smart Chat - No Research": false, "Solve Math Problem": false, "Write a Poem": false, "Generate Task Chain without Research": false, "Smart Chat": false, "Generate Smart Task Chain": false, "Ask Helper Agent for Help": false, "Smart Instruct": false, "Smart Prompt": false, "Generate Task Chain": false, "Generate Image": false, "Chat with Voice": false, "Transcribe Audio from File": false, "Transcribe Base64 Audio": false, "Read Audio from File with Huggingface": false, "Read Audio with Huggingface": false, "Transcribe Base64 Audio with Huggingface": false, "Create Table in Postgres Database": false, "Insert Row in Postgres Database": false, "Select Rows in Postgres Database": false, "Update Rows in Postgres Database": false, "Delete Rows in Postgres Database": false, "Custom SQL Query in Postgres Database": false, "Get Database Schema from Postgres Database": false, "Get Table Schema from Postgres Database": false, "Speak with TTS with Streamlabs Text to Speech": false, "Generate Image with Stable Diffusion": false, "Speak with TTS Using Elevenlabs": false, "Clone Github Repository": false}, "settings": {"provider": "gpt4free", "embedder": "default", "AI_MODEL": "gpt-3.5-turbo", "AI_TEMPERATURE": "0.7", "AI_TOP_P": "1", "MAX_TOKENS": "4096", "helper_agent_name": "gpt4free", "WEBSEARCH_TIMEOUT": 0, "WAIT_BETWEEN_REQUESTS": 1, "WAIT_AFTER_FAILURE": 3, "stream": false, "WORKING_DIRECTORY": "./WORKSPACE", "WORKING_DIRECTORY_RESTRICTED": true, "AUTONOMOUS_EXECUTION": true, "PERSONA": ""}}`

### Steps to Reproduce the Bug

Adding a new provider, (tried with openai and Custom providers), Filling out the fields, selecting commands and hitting update agent.

### Expected Behavior

New agent is created with proper settings written to disk

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Are you using the Streamlit UI or the NextJS UI?

**Comment by kratosok** [comment]
Streamlit I would guess 8501?
