### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#1071]
### Description
default embedder
Run Agent interaction with Chains "Generate Task Chain"

```
agixt-agixt-1                  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
agixt-agixt-1                  |     return await dependant.call(**values)
agixt-agixt-1                  |   File "/agixt/endpoints/Chain.py", line 137, in add_chain
agixt-agixt-1                  |     Chain(user=user).add_chain(chain_name=chain_name.chain_name)
agixt-agixt-1                  |   File "/agixt/fb/Chain.py", line 76, in add_chain
agixt-agixt-1                  |     file_path = get_chain_file_path(chain_name=chain_name)
agixt-agixt-1                  |   File "/agixt/fb/Chain.py", line 37, in get_chain_file_path
agixt-agixt-1                  |     os.mkdir(folder_path)
```

### Steps to Reproduce the Bug

same as above

### Expected Behavior

don't know

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
You may need to make a shorter chain name.  The max character length of a file path shouldn't exceed 256 characters.
