### ISSUE TITLE
failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2396362875/Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by namen3645** [Josh-XT/AGiXT#1075]
### Description

    ___   _______ _  ________
   /   | / ____(_) |/ /_  __/
  / /| |/ / __/ /|   / / /
 / ___ / /_/ / //   | / /
/_/  |_\____/_//_/|_|/_/

----------------------------------------------------
Visit our documentation at https://AGiXT.com
Welcome to the AGiXT Installer!
Please choose an option:
  1. Run AGiXT (Recommended)
  2. Run AGiXT with Text Generation Web UI (NVIDIA Only)
  3. Run AGiXT with Text Generation Web UI and Stable Diffusion (NVIDIA Only)
Developer Only Options (Not recommended or supported):
  4. Run AGiXT from Main Branch
  5. Run AGiXT from Main Branch + Addons (NVIDIA Only)
  6. Run AGiXT without Docker
Manage:
  7. Enable Automatic Updates
  8. Exit

Enter your choice: 3
Confirmed NVIDIA Container Toolkit is installed.
Running Docker install...
Starting Docker Compose...
Building text-generation-webui
[+] Building 0.0s (2/2) FINISHED                                                                         docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2B                                                                                 0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2396362875/Dockerfile: no such file or directory
ERROR: Service 'text-generation-webui' failed to build : Build failed
root@DESKTOP-NK2R4R0:~/AGiXT#

### Steps to Reproduce the Bug

1.Use Ubuntu 22.04 in WSL Windows 10
2. Run command:
git clone https://github.com/Josh-XT/AGiXT
cd AGiXT
./AGiXT.sh
3. Select Run AGiXT with Text Generation Web UI (NVIDIA Only)
4. Get error: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2396362875/Dockerfile: no such file or directory

### Expected Behavior

AGiXT running succesfully 

### Operating System

- [X] Linux
- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by nengisuls** [comment]
Also just had this error. same parameters but latest popos

**Comment by gpiotti** [comment]
it seems in docker-compose-local-nvidia.yml
the dockerfile should be:

```
text-generation-webui:
    build:
      context: text-generation-webui/.
      dockerfile: docker/nvidia/Dockerfile   <-- 
```
      
instead of:

```
text-generation-webui:
    build:
      context: text-generation-webui/.
      dockerfile: docker/Dockerfile
```

**Comment by Josh-XT** [comment]
The docker-compose files have been updated to point to the path where the Dockerfile was moved in their repository.
