### ISSUE TITLE
Api changed

### ISSUE THREAD

**Issue by KrustyDerClown** [Josh-XT/AGiXT#1076]
### Description

The Api of oobabooga/text-generation-webui changed, see https://github.com/oobabooga/text-generation-webui/releases/tag/snapshot-2023-11-12

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/v1/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e55eeb610>: Failed to establish a new connection: [Errno 111] Connection refused'))

### Steps to Reproduce the Bug

Hit something in Chat window and see output on terminal above

### Expected Behavior

get response from oobabooga/text-generation-webui 

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Ooba API and install has changed a lot on me, I've discontinued support.
