### ISSUE TITLE
Error response from daemon: failed to create task for container

### ISSUE THREAD

**Issue by blacksocket** [Josh-XT/AGiXT#1079]
### Description

Description
run ./AGiXT.sh with option 2. Run AGiXT with Text Generation Web UI (NVIDIA Only)
![image](https://github.com/Josh-XT/AGiXT/assets/13651344/9f8dc18f-3489-4be5-9f42-4ab253284cef)

[+] Running 4/0
 ✔ Container agixt-text-generation-webui-1  Created                                                                                                                                                                                     0.0s
 ✔ Container agixt-agixt-1                  Created                                                                                                                                                                                     0.0s
 ✔ Container agixt-streamlit-1              Created                                                                                                                                                                                     0.0s
 ✔ Container agixt-nextjs-1                 Created                                                                                                                                                                                     0.0s
Attaching to agixt-agixt-1, agixt-nextjs-1, agixt-streamlit-1, agixt-text-generation-webui-1
agixt-agixt-1                  | Starting AGiXT...
agixt-agixt-1                  | INFO:     Uvicorn running on http://0.0.0.0:7437 (Press CTRL+C to quit)
agixt-agixt-1                  | INFO:     Started parent process [8]
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown

### Steps to Reproduce the Bug

fresh clone AGiXT and run ./AGiXT.sh with option 2

### Expected Behavior

no error

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [x] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by blacksocket** [comment]
Created by mistake.

**Comment by blacksocket** [comment]
I found also:
:~/projects/AGiXT$ dmesg | grep NVRM
[    4.253959] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  520.61.05  Thu Sep 29 05:30:25 UTC 2022
[ 3436.455442] NVRM: API mismatch: the client has the version 535.129.03, but
               NVRM: this kernel module has the version 520.61.05.  Please
               NVRM: make sure that this kernel module and all NVIDIA driver
               NVRM: components have the same version.
[87444.408342] NVRM: API mismatch: the client has the version 535.129.03, but
               NVRM: this kernel module has the version 520.61.05.  Please
               NVRM: make sure that this kernel module and all NVIDIA driver
               NVRM: components have the same version.
[100631.878431] NVRM: API mismatch: the client has the version 535.129.03, but
                NVRM: this kernel module has the version 520.61.05.  Please
                NVRM: make sure that this kernel module and all NVIDIA driver
                NVRM: components have the same version.

**Comment by Josh-XT** [comment]
This is the Ooba container having issues communicating with your Nvidia driver as far as I can tell.  I would recommend making sure your driver is up to date and that you have the necessary cuda toolkits installed. If you have installed them recently, try a reboot.

**Comment by blacksocket** [comment]
Seems this was the root cause, so we can close the case. 
Thank you!
