### ISSUE TITLE
It is impossible to use the interface from a browser on another machine.

### ISSUE THREAD

**Issue by Guerdal** [Josh-XT/AGiXT#1080]
### Description

When I launch the Docker project, the backend interface (port 8051) works, but when I try to connect to the frontend (http://IP_of_Server:24498), an error message appears (Application error: a client-side exception has occurred (see the browser console for more information).).
If I use the console, there are attempts to access the URL http://localhost:24498.

### Steps to Reproduce the Bug

1. Launch ./AGiXT.sh 
2. Choose Option 1
3. All the dockers launch
4. Open web browser on an another machine in the local network to http://IP_of_SERVER:8051 => OK
5. Open web browser on an another machine in the local network to http://IP_of_SERVER:24498 => Application error: a client-side exception has occurred (see the browser console for more information).

### Expected Behavior

Open web browser to http://IP_of_SERVER:24498 => go to the frontend Interface

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
The one on 24498 is only accessible from the server it is running on because it looks for AGiXT at http://localhost:7437, which it will not be at for any other computer that isn't running the AGiXT back end. That interface is still mostly experimental which is why it is only accessible on the server that AGiXT is running on.

**Comment by Guerdal** [comment]
Alright, I misunderstood that part of the project. So the next question is: Which interface should be used to interact with AGixt from another machine ?

**Comment by Josh-XT** [comment]
> Alright, I misunderstood that part of the project. So the next question is: Which interface should be used to interact with AGixt from another machine ?

The Streamlit web UI is on port 8501 and should be accessible from other machines. You can also access AGiXT over API on port 7437.
