### ISSUE TITLE
Unprocessable Entity

### ISSUE THREAD

**Issue by short-circuit** [Josh-XT/AGiXT#1081]
### Description

When running a "Learn from Github", a 422 HTTP error is returned:
```
"POST /api/agent/gpt4free/learn/github HTTP/1.1" 422 Unprocessable Entity 
```
UI says training done, obviously that is not true.

### Steps to Reproduce the Bug

1. Go to agent training
2. Select training source -> Github Repository
3. Enter any public repo
4. Press on train from github repository

### Expected Behavior

Working as intended

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [x] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello, this is resolved in the latest version. Somehow a typo of a random comma for in and broke it. Resolved now.
