### ISSUE TITLE
Ngrok Tunnels to use with AGIXT

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1089]
### Feature/Improvement Description

Sometimes you don't want to port forward for security reasons and just want to expose AGIXT through Ngrok. I also think this feature would be nice to add because say you're working remotely from a server and you can't port forward again for whatever reason that might be you can just spin up ngrok and have it expose AGiXT for you.

### Proposed Solution

To add Ngrok in the setup script 

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Added in #1136
