### ISSUE TITLE
Frontend: Warning When Building and Error When 'npm start'

### ISSUE THREAD

**Issue by lightningRalf** [Josh-XT/AGiXT#109]
Hi there, 
I just built the frontend on linux with npm / frontend #0.8.0
just found the following warning:
```
./components/agent/AgentObjective.js
20:8 Warning: Reacht Hook useCallback has a missing dependency: ' objective'. Either include it or remove the dependency array.
You can also replace multiple useState variables with useReducer if 'setRunning' needs the current value of ' objective'. 

warn - found lockfile missing swc dependencies, patching...
```
and then it finished.
But on entry "npm start"
I got an error:
```
Error: could not find a production build in the '.next' directory. try building your app with ' next build' , before starting the production server.
``` 

I get three commands that I should do:
```
sudo apt install mailutils-mh
sudo apt install mmh
sudo apt install nmh
``` 
When I install them all, a gui pops up for an mailservice. But I cannot use 'no configuration' and I am stuck in a loop there.

Thanks in advance. Greetings from Germany

**Comment by CRCODE22** [comment]
Same issue.

**Comment by JamesonRGrieve** [comment]
`next` is a JS command. It has to be run through Node or similar. That `warn` shouldn't cause an issue but it's not occurring for me on Windows. Fresh clone does it as well?
