### ISSUE TITLE
Implement command validation/helper to stop agents from running arbitrary commands

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1111]
### Feature/Improvement Description

When running Gemini Pro I've noticed its trying to run random commands that don't exist or sometimes agents clearly don't know what commands they can use sometimes and what each command does. This is a partial reason why I think this should be implemented.

### Proposed Solution

It would be helpful to have a command validation helper. If an agent attempts an unavailable command, the helper should clearly state the command cannot be executed and then automatically provide a list of enabled commands tailored to that agent's permissions. This mirrors the helpful '--help' prompt found in many terminal programs.

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
We have helper agents. In agent config, you can set `helper_agent` to whichever agent name you want it to be able to ask for help to, then enable the command for that agent to be able to ask for help.
