### ISSUE TITLE
The code is not up to date and there are many errors after running it

### ISSUE THREAD

**Issue by linkingnie** [Josh-XT/AGiXT#1117]
### Description

The code is not up to date and there are many errors after running it. It seems that webui and AGiXT core do not match. Hopefully the latest code can be uploaded instead of the docker container.

### Steps to Reproduce the Bug

1、Run app.py
2、Run web ui main.py
3、Click Agent management

### Expected Behavior

No errors

### Operating System

- [ ] Linux
- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello. Running app.py directly is the incorrect way to run it. Please follow the quick start guide on agixt.com
