### ISSUE TITLE
 Log verbosity environment variable

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1179]
### Feature/Improvement Description

I wanna see the responses in the agent you can tell if the agent is hallucinating and also its just fun to watch it work...

### Proposed Solution

add an option to enable this

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Added in #1180 with details on how to change it.
