### ISSUE TITLE
Slow Page Switching

### ISSUE THREAD

**Issue by lightningRalf** [Josh-XT/AGiXT#119]
### Title

When I switch pages in the frontend, it takes more than a second

### Description

When clicking from providers to agents I have to wait around 2,5 seconds to load the new page.

### Steps to Reproduce

localhost:3000/agent
click to prompts
till localhost:3000/prompts come up, it takes 2.5 secons

### Expected Behavior

sub 0.5 seconds between site switch

### Actual Behavior

switching takes more than 2.5 seconds

### Additional Context

VM ubuntu on about 20% ressources

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by CRCODE22** [comment]
I do notice that the new gui is responding slower on my computer as well compared to the older gui.

**Comment by JamesonRGrieve** [comment]
Are you running the backend and frontend on the same machine? Mine loads <0.5 seconds.
