### ISSUE TITLE
Frontend / Agent-LLM / All-commands

### ISSUE THREAD

**Issue by lightningRalf** [Josh-XT/AGiXT#121]
### Title

Not being able to add only some commands to the control agent

### Description

Agent-LLM has always access to all commands

![image](https://user-images.githubusercontent.com/126403501/234670869-63fa5a09-cd30-4cc7-b82d-71534a54ef03.png)

### Steps to Reproduce

1. go to localhost:3000/agent/Agent-LLM
2. look at the All Commands / always on,
3. when I click on the toggle button

### Expected Behavior

1. either make it toggle able, or hide it
2. if neither is possible, than show an explanation why

### Actual Behavior

when I click on the toggle button:
1. nothing happens, 
2. no tool tip, 
3. no explanation

### Additional Context

Ubuntu in VM
Firefox as browser
localhost:3000:/agent/Agent-LLM

V1.0.10

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by JamesonRGrieve** [comment]
This should have been fixed in #78. Are you up to date?
