### ISSUE TITLE
I don’t understand, is there something wrong with your discord channel or have you blocked me from it?

### ISSUE THREAD

**Issue by AliveDedSec** [Josh-XT/AGiXT#1219]
### Description

I don’t understand what happened, I was kicked out of your AGIXT discord channel and I can’t find it in the search or log in through the invitation https://discord.gg/vfXjyuKZ I thought maybe you blocked me?  But I found no reason in my actions to block me for this.

### Operating System

- [X] Linux
- [ ] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] PowerShell 7.X is installed and the version in use on the host machine.
- [X] Docker is installed and running on the host machine.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by Josh-XT** [comment]
You've been removed from the server. If you decide at any point that you would like to communicate with people in a less condescending manner, I will consider allowing you back, but I am not going to be spoken to in the way that you speak to me. I work hard to bring this to people for free and I do my best to support it alone, I'm not going to be treated poorly for my efforts even if my efforts are not always good enough. I'm happy to receive feedback from bug reports, but I don't need someone leaving paragraphs of why my software is terrible in my discord while I sleep because of your own misconfiguration problems.

**Comment by AliveDedSec** [comment]
> You've been removed from the server. If you decide at any point that you would like to communicate with people in a less condescending manner, I will consider allowing you back, but I am not going to be spoken to in the way that you speak to me. I work hard to bring this to people for free and I do my best to support it alone, I'm not going to be treated poorly for my efforts even if my efforts are not always good enough. I'm happy to receive feedback from bug reports, but I don't need someone leaving paragraphs of why my software is terrible in my discord while I sleep because of your own misconfiguration problems.

If I have offended you in any way, then I sincerely ask for your forgiveness.  And I’m ready to apologize publicly, including in discord.  I sincerely don’t understand what caused such a negative reaction from you?  Perhaps it's a difference in mentality?  Or is this possibly a bug in the GOOGLE online translator I'm using?  I never allowed myself to stoop to insulting my interlocutors.  Have I insulted AGIXT?  On the contrary, I always mentioned that I admire what you do, and I like what you do.  I was just writing you bug reports and letting you know what was going on.  
Perhaps due to translation difficulties you misunderstood my humor?  I assure you that there was no negativity on my part.  I understand English very poorly, my native Russian.  Perhaps my translations sounded offensive to you, but I assure you I had no such intention.

**Comment by Josh-XT** [comment]
We may have a difference in sense of humor, but I don't find the humor in posting in my public discord that the maintainer (me) will not implement good ideas for 1-2 years and that I must comply with your requirements for make magic happen and allow you to pull docker containers without an internet connection, or to use some obscure container management software that doesn't allow you to use the latest version of docker. I don't find humor in my time being wasted or having my hard work talked about as if it is trash. I also don't find humor in things like the last message you posted telling people to go use some other software because mine won't ever work because you can't figure things out.

If you have a problem, post a bug report and let me know what you were doing when the problem came up.

**Comment by AliveDedSec** [comment]
Now I don’t see my messages on discord, and I can’t access them to analyze them and understand what could be the matter.  I could answer you on each point if you would show me where I offended you.  Decipher what I meant.  Unfortunately, I don't have the opportunity to do this right now.  I have never had a negative attitude towards you or AGIXT.  On the contrary, I am a positive person in life.  And I think I’ve said many times that I like AGIXT and what you do, I really appreciate your work.  And I said that I understand that you are fighters on the front line of the war for AGI.  For my part, I tried to give advice and suggestions on how to make AGIXT better.  Still, I am sure that these are errors of the GOOGLE translator, and the difference in mentality.  I am sure that because of this you simply misunderstood me.  GOOGLE sometimes gives diametrically opposite translations in meaning, not to mention cultural differences.  And I have to quickly edit the sent message in horror.

**Comment by AliveDedSec** [comment]
Я никогда не говорил о вашей работе как о мусоре. Это точно. Я недавно рассказывал вам, что только недавно понял насколько тяжело разрабатывать приложения качественные и без ошибок. Я всегда с уважением относился к людям труда и обычным рабочим, я сам из простой семьи и работаю руками и головой. Я иногда делаю самую грязную работу самостоятельно. Так что я никогда бы не позволил себе смеяться над чьей то работой со злостью.  Только добрый юмор. Я лишь пытался расшифровать свою точку зрения, и тот юмор который я использовал в моей стране является абсолютно безобидным. Просто шутка, не более того. У нас есть такая поговорка "Обещанного три года ждут"  Я использовал ее вольную интерпритацию. Можете загуглить сами   https://aif.ru/society/education/chto_oznachaet_poslovica_obeshchannogo_tri_goda_zhdut

**Comment by AliveDedSec** [comment]
Я настаиваю на ошибках перевода и том что вы меня неправильно поняли, неправильная передача смыслов. Если вам это нужно, я готов принести пуюличные извенения в дискорде. Я даже готов опубликовать в канале сообщение от своего имени, которое вы напишите самостоятельно, чтобы пользователи лучше поняли его.  С большим уважением к вам!

**Comment by AliveDedSec** [comment]
публиковать в своем публичном дискуссионе сообщение о том, что мейнтейнер (я) не будет реализовывать хорошие идеи в течение 1-2 лет и что я должен выполнять ваши требования, чтобы сделать произойдет волшебство, и вы сможете извлекать контейнеры Docker без подключения к Интернету или использовать какое-то малоизвестное программное обеспечение для управления контейнерами, которое не позволяет вам использовать последнюю версию Docker. Я не нахожу юмором то, что мое время тратится впустую или когда о моей тяжелой работе говорят как о мусоре. Я также не нахожу юмора в таких вещах, как ваше последнее сообщение, в котором вы советуете людям использовать другое программное обеспечение, потому что мое никогда не будет работать, потому что вы не можете во всем разобраться.  

  Все это сообщение целиком убеждает меня полностью, что вы меня поняли абсолютно неправильно, не так как я рассчитывал.  Моя версия докера последняя из доступных и стабильных Docker version 26.1.3, build b72abbb6f0
.  Portainer является известным в сообществах и не вызывает никаких проблем в работе докера.  Вашу работу я ценю абсолютно также, как свою собственную. Я ценю благородный труд любого человека, иногда даже больше чем свой собственный.  Я не мог советовать людям что то другое, кроме AGIXT. Потому что на данный момент у AGIXT нет аналогов.  Ну или просто я о них не знаю. Есть слабые подобия, которые вообще не работают. И там нет функций как у AGIXT. Я просто пыталься привести наглядные примеры . Расшифровать свою точку зрения и свое видение ситуации. Но видимо вы во многом поняли меня абсолютно не так, как я рассчитывал. Совершенно другие смыслы.

**Comment by AliveDedSec** [comment]
В заключение хочу сказать, что все мои сообщения здесь и в дискорде были направлены лишь на то, чтобы помочь сделать AGIXT лучше. И абсолютно никакого негатива мной не подразумевалось. Были просто замечания, которые я считал важными.

**Comment by Josh-XT** [comment]
There is no need for any public apology. If your commentary on the situation of things is not being translated well, I would try to limit what you are translating to the problem you're having and error logs and less of what you think about the problem or me.

**Comment by AliveDedSec** [comment]
> Никаких публичных извинений не требуется. Если ваш комментарий о положении дел переводится плохо, я бы постарался ограничить то, что вы переводите, проблемой, с которой вы столкнулись, и журналами ошибок, а не тем, что вы думаете о проблеме или обо мне.

Вы ни разу не упоминали о том, что есть какие то ограничения на канале. Во всяком случае я об этом никогда не слышал. Я просто использую этот канал как оперативную отправку ошибок и своего мнения об AGIXT. Может тогда использовать общение через личные сообщения? Мне просто и в голову не могло прийти, что конструктивная критика приложения будет воспринята вами так негативно. Тем более что канал не очень активный, и я не думал что это будет мешать кому либо из пользователей. Я думал что они будут видеть что идет работа над AGIXT и это наоборот вызовет интерес, мне казалось что это лучше чем мертвый канал.

**Comment by AliveDedSec** [comment]
Я считаю лично, во всяком случае у нас это считается нормальным, когда люди критикуют что-то конструктивно. У нас есть негласный закон - критикуешь что то, тогда предложи как это улучшить. Если человек скажет просто, что какое то приложение дерьмо - это неправильно. Он должен рассказать что именно не так, и как он предлагает это улучшить.

**Comment by Josh-XT** [comment]
Constructive criticism is fine, but it is not constructive to say things like it will take years to get the maintainer to do something or that people should go use something else because this isn't working for you, or that you're never updating once you get things working because of me. I think keeping these opinions to yourself will be most beneficial, especially if the translation of these opinions is coming off as disrespectful as it does. The ban was lifted on discord, there is no need to talk about this any further. My focus is on the development of the software and will remain there.
