### ISSUE TITLE
Front End: Chat does not work

### ISSUE THREAD

**Issue by lightningRalf** [Josh-XT/AGiXT#122]
### Title

Unexpected behavior after entering a message for an Agent

### Description

![image](https://user-images.githubusercontent.com/126403501/234673412-81b16055-9af0-40c2-ae58-440bc2fcf879.png)

### Steps to Reproduce

1. Go to localhost:3000/agent
2. create a new agent
3. turn off all commands
4. enter message in textfield
5. hit 'message agent'
6. receive error

### Expected Behavior

getting a message in return

### Actual Behavior

getting an error handle as seen above in the screenshot

### Additional Context

Ubuntu in VM
Firefox as browser
V1.0.11

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by Josh-XT** [comment]
Hello!  Chat functionality is currently disabled and is there as a placeholder while we build the functionality.  One of then next versions of the front end should bring this functionality to life since the back end is caught up on it now.  Stay tuned, I'll leave this open for visibility.

**Comment by JamesonRGrieve** [comment]
The send message button is disabled...? How did you send one?
