### ISSUE TITLE
Error increasing token counts: Textual SQL expression 'cbb380f8-c64d-4a00-bed4-6...' should be explicitly declared as text('cbb380f8-c64d-4a00-bed4-6...')

### ISSUE THREAD

**Issue by llvm-x86** [Josh-XT/AGiXT#1237]
### Description

2024-08-20 20:34:06,686 | WARNING | Error increasing token counts: Textual SQL expression 'cbb380f8-c64d-4a00-bed4-6...' should be explicitly declared as text('cbb380f8-c64d-4a00-bed4-6...')

### Operating System

- [X] Linux
- [ ] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] Python 3.10.X is installed and the version in use on the host machine.
- [X] The latest version of Docker is installed and running on the host machine.
- [X] I am using the latest stable version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by Josh-XT** [comment]
Hello, this error has been resolved. Thank you for reporting!
