### ISSUE TITLE
More Conversation Managing

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1238]
### Feature/Improvement Description

I would like to pretty much splice a conversation with another and this would be nice for manual intervention with AGiXT instead of having a task chain run and just get lost since it can have no idea what it needs to do with some models. This can help with testing the capabilities and learning how to better prompt it so that way it can chain off and grab the conversation and figure out whats up and continue off.

### Proposed Solution

A built in feature to the backend that would just combine and then rename it to say spliced with conversation x and y and then just combine one on top of the other or vice versa. 

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Created a `fork_conversation` function, exposed in the API now as well with tests created and passing.

https://github.com/Josh-XT/AGiXT/pull/1241

Created an issue on AGiXT Interactive repository to add the front end feature.

https://github.com/JamesonRGrieve/AGiXT-Interactive/issues/52
