### ISSUE TITLE
SQLITE | Task Chain is blank

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1246]
### Description

Running a clean install and also by using the install script to setup AGiXT with docker, Task Chain is showing blank no other chains are showing this.

![image](https://github.com/user-attachments/assets/24294dd4-d6ad-4a8b-bf9f-5f1104e66633)

### Operating System

- [X] Linux
- [ ] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] Python 3.10.X is installed and the version in use on the host machine.
- [X] The latest version of Docker is installed and running on the host machine.
- [X] I am using the latest stable version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by Josh-XT** [comment]
Fixed
