### ISSUE TITLE
Command Execution Broken in Chains

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#1250]
### Description

Running task chains there is no message saying that there has been a command has executed successfully in the task chains when running them. When I run the instruct mode they work just fine in being able to execute the commands its shows a message that the command has executed successfully and the command output.

### Operating System

- [X] Linux
- [ ] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] Python 3.10.X is installed and the version in use on the host machine.
- [X] The latest version of Docker is installed and running on the host machine.
- [X] I am using the latest stable version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by Josh-XT** [comment]
This should be resolved in v1.6.16.
