### ISSUE TITLE
None of the actions in Prompt Management tab work properly

### ISSUE THREAD

**Issue by maxiy01** [Josh-XT/AGiXT#1252]
### Description

Trying to "Create New Prompt" returns this error: 
```
Exception: Unable to retrieve data. 'message'
Traceback:

File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
File "/app/pages/4-Prompt_Management.py", line 87, in <module>
    ApiClient.add_prompt(
File "/usr/local/lib/python3.10/site-packages/agixtsdk/__init__.py", line 690, in add_prompt
    return self.handle_error(e)
File "/usr/local/lib/python3.10/site-packages/agixtsdk/__init__.py", line 56, in handle_error
    raise Exception(f"Unable to retrieve data. {error}")
 ```
 
Modify or Delete action says that prompt updated/deleted withot throwing error,, but no changes occur. Adding new category also doesn't work

### Operating System

- [ ] Linux
- [X] Windows
- [ ] MacOS

### Acknowledgements

- [X] I am NOT trying to use localhost for providers running outside of the docker container.
- [X] I am NOT trying to run AGiXT outside of docker, the only supported method to run it.
- [X] Python 3.10.X is installed and the version in use on the host machine.
- [X] The latest version of Docker is installed and running on the host machine.
- [X] I am using the latest stable version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.

**Comment by maxiy01** [comment]
Importing prompt from txt throws same error as creating new one in usual way

**Comment by birdup000** [comment]
Hello thank you for reporting the issue,

the issue has been resolved in commit 149465284e22576ad65141a712b0149c37b17b6a, which is now merged into the main branch. 

Update your docker-compose file to use the 'main' branch instead of 'latest' and restart your containers with the start.py script.

**Comment by maxiy01** [comment]
Can confirm it's working, thank you.

**Comment by birdup000** [comment]
Thank you too!
