### ISSUE TITLE
Add tests for each file type on learn_file

### ISSUE THREAD

**Issue by Josh-XT** [Josh-XT/AGiXT#1263]
# Add tests for each file type on `learn_file`

Modify [The Test Notebook](https://github.com/Josh-XT/AGiXT/blob/main/tests/endpoint-tests.ipynb) to include a `learn_file` test for the missing file types. We will want to add the additional tests after `Have the Agent Learn from a File`.  Note: This excludes images and plain-text files as they're already tested.

- [ ] PDF (.pdf)
- [ ] Microsoft PowerPoint (.ppt, .pptx)
- [ ] Microsoft Word (.doc, .docx)
- [ ] Microsoft Excel (.xlsx, .xls)
- [ ] CSV (.csv)
- [ ] ZIP (.zip)

Example to download a CSV file and learn from it.

```python
import requests

csv_url = "https://people.sc.fsu.edu/~jburkardt/data/csv/hurricanes.csv"
response = requests.get(csv_url)
# Save the file
learn_file_path = os.path.join(os.getcwd(), "hurricanes.csv")
with open(learn_file_path, "wb") as f:
    f.write(response.content)
learn_file_content = base64.b64encode(response.content).decode("utf-8")

file_learning = agixt.learn_file(
    agent_name=agent_name,
    file_name=learn_file_path,
    file_content=learn_file_content,
    collection_number="0",
)
```

**Comment by birdup000** [comment]
#1266 Pr is there but will add all those file types mentioned
