### ISSUE TITLE
Nesting commands

### ISSUE THREAD

**Issue by hlohaus** [Josh-XT/AGiXT#294]
### Problem Description

I created locally a patch for nesting commands.
With my changes we can put commands together.
For example: we could combined four commands:

1. The agent search for a website with needed informations.
2. The agent fetch the text content from the website.
3. The agent created a summary from the text.
4. The agent write the text summary to a file.

Example json:
```
{
    "commands": {
        "_write_to_file": {
            "filename": "example.txt",
            "text": {
                "_scrape_text": {
                    "url": "http://example.com",
                }
            }
        }
    }
}
```

I added an underscore to the commands, so we can know which commands are meant to be executed.

Also i changed for better results the list of available commands to json:
```
{
    "commands": {
        "_command1": {
            "_": "Description",
            "arg1": "val1",
            "arg2": "val2"
        },
        "_write_to_file": {
            "_": "Write content to a file",
            "filename": "example.txt",
            "text": ""
        },
        "_get_contents": {
            "_": "Read content from a website",
            "url": "http://example.com",
        }
     }
}
```
Isn't it a good improvment?

### Proposed Solution

See description 

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
The read/write file and browse web are commands that would get passed in with the list of commands.  It should only be responding with the commands it wants to execute.  Feel free to do a pull request and I can take a look.

**Comment by hlohaus** [comment]
Yes, only the commands from the list in the prompt will be used.

Currently the Aai can't use the results from the commands. It adds all necessary commands to the response, but the results of the execution only appears in the log. The AI doesn't use it for the next Task. And often it write only placeholder in the arguments. With my changes, it automatically create a chain of commands. Instead of placeholder, it can use other command to solve arguments.
