### ISSUE TITLE
Streamlit Tasks - Illegal instruction

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#371]
### Description

Running with Docker on WSL2 Ubuntu 22.04 LTS Windows 11 

### Steps to Reproduce the Bug

1.Start Docker Container Streamlit
2.Access the webui on Streamlit
3.Create Agent (Bard,Palm,gpt4free)
4.Go to tasks
5.Create a task and start it 
6.Watch logs Error will show on the logs on streamlit backend 

&& you can also try with chat and will probably show the error there too.

### Expected Behavior

I expect the tasks to function and run properly. 

### Actual Behavior

agent-llm-backend-streamlit-1  | Illegal instruction
agent-llm-backend-streamlit-1 exited with code 132

### Additional Context / Screenshots

agent-llm-backend-streamlit-1  | 2023-05-18 00:09:06.396 Load pretrained SentenceTransformer: all-mpnet-base-v2
agent-llm-backend-streamlit-1  | 2023-05-18 00:09:08.103 Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
agent-llm-backend-streamlit-1  | 2023-05-18 00:09:08.105 Running Chroma using direct local API.
agent-llm-backend-streamlit-1  | 2023-05-18 00:09:08.107 Using embedded DuckDB with persistence: data will be stored in: agents/bees/memories
agent-llm-backend-streamlit-1  | Illegal instruction
agent-llm-backend-streamlit-1 exited with code 132

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by localagi** [comment]
@Josh-XT you can assign to me, i'll test it

**Comment by med4u** [comment]
Same problem, same context for me

**Comment by Josh-XT** [comment]
This issue appears to be specifically with the Docker Streamlit.  I'm hearing other reports of the same, but cannot reproduce running streamlit local.

**Comment by DIGist** [comment]
Mine does this too, using docker:

> agent-llm-backend-streamlit-1  | 2023-05-18 07:31:11.423 Load pretrained SentenceTransformer: all-mpnet-base-v2
> agent-llm-backend-streamlit-1  | 2023-05-18 07:31:12.951 Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
> agent-llm-backend-streamlit-1  | 2023-05-18 07:31:12.953 Running Chroma using direct local API.
> agent-llm-backend-streamlit-1  | 2023-05-18 07:31:12.954 Using embedded DuckDB with persistence: data will be stored in: agents/test5/memories
> agent-llm-backend-streamlit-1  | Illegal instruction (core dumped)
> agent-llm-backend-streamlit-1 exited with code 132

**Comment by UndefinedConstant** [comment]
Having it on Pop! 22.04 using docker, running in VMware Workstation 15, on Win10 Host w. WSL1
both backends exit with code 132, if trying to chat
hugchat and gpt4free (haven't tested the others)

**Comment by localagi** [comment]
> This issue appears to be specifically with the Docker Streamlit. I'm hearing other reports of the same, but cannot reproduce running streamlit local.
> 
> @localagi can you take a look at the docker stuff for streamlit when you have a moment?

Jep, all the time learning how to build the AGI-specialities, currently working on it here to not cause disturbance on the main project  https://github.com/localagi/AGiXT-docker/actions

**Comment by localagi** [comment]
@greengeckowizard experienced this also and hunting the bug

**Comment by adam-eastes** [comment]
> Having it on Pop! 22.04 using docker, running in VMware Workstation 15, on Win10 Host w. WSL1 both backends exit with code 132, if trying to chat hugchat and gpt4free (haven't tested the others)

I am also having this issue running on VMware Workstation

**Comment by localagi** [comment]
@adam-eastes @UndefinedConstant @med4u @DIGist @greengeckowizard Please check out if the problem still persists.

Remember to pull the lastest image versions (see README)
It should be fixed by now.

As a workaround, if the error still persists, you can use the files and containers from https://github.com/localagi/AGiXT-docker

**Comment by localagi** [comment]
@Josh-XT after a period of time, you can close this at will. 24hrs no more error reports. (I cannot close)

**Comment by DIGist** [comment]
This appears to be fixed for me now, Now i'm dealing with another unrelated issue. Thanks!

**Comment by greengeckowizard** [comment]
> @Josh-XT after a period of time, you can close this at will. 24hrs no more error reports. (I cannot close)

I can close if this happens again I can reopen it ig.
