### ISSUE TITLE
Newer Builds with /src/ folder give error "No such file or directory: '/app/src/agent-llm/version"

### ISSUE THREAD

**Issue by mindwellsolutions** [Josh-XT/AGiXT#387]
### Description

Thank you for putting together such a powerful platform. I'm beyond excited to start using it, ran into this issue on the newer builds. I went back to try v1.3.0 and it didn't have this issue (files/folders were in root instead of /src/) but the network connection wasn't working.

On the newer builds (with /src/ folder) I get this error saying it can't find "/app/src/agent-llm/version". 
**However if I:** nano app/src/agent-llm/version | **it is able to find open and view the version file without issue**
2 lines above. It was able to open /app/app.py . 

**Any ideas what how to fix this? Full Error Text Below:**

docker compose --profile all up
[+] Running 4/4
 ✔ Network agixt-1140-beta_default                Created                                                                                                              0.6s 
 ✔ Container agixt-1140-beta-backend-streamlit-1  Created                                                                                                              0.9s 
 ✔ Container agixt-1140-beta-backend-1            Created                                                                                                              0.9s 
 ✔ Container agixt-1140-beta-frontend-1           Created                                                                                                              0.2s 
Attaching to agixt-1140-beta-backend-1, agixt-1140-beta-backend-streamlit-1, agixt-1140-beta-frontend-1
agixt-1140-beta-frontend-1           | yarn run v1.22.19
agixt-1140-beta-frontend-1           | $ next start
agixt-1140-beta-frontend-1           | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
agixt-1140-beta-backend-streamlit-1  | 
agixt-1140-beta-backend-streamlit-1  | Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
agixt-1140-beta-backend-streamlit-1  | 
agixt-1140-beta-backend-streamlit-1  | 
agixt-1140-beta-backend-streamlit-1  |   You can now view your Streamlit app in your browser.
agixt-1140-beta-backend-streamlit-1  | 
agixt-1140-beta-backend-streamlit-1  |   Network URL: http://172.22.0.3:8501
agixt-1140-beta-backend-streamlit-1  |   External URL: http://68.226.89.181:8501
agixt-1140-beta-backend-streamlit-1  | 
agixt-1140-beta-backend-1            | Traceback (most recent call last):
agixt-1140-beta-backend-1            |   File "/usr/local/bin/uvicorn", line 8, in <module>
agixt-1140-beta-backend-1            |     sys.exit(main())
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
agixt-1140-beta-backend-1            |     return self.main(*args, **kwargs)
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
agixt-1140-beta-backend-1            |     rv = self.invoke(ctx)
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
agixt-1140-beta-backend-1            |     return ctx.invoke(self.callback, **ctx.params)
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
agixt-1140-beta-backend-1            |     return __callback(*args, **kwargs)
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
agixt-1140-beta-backend-1            |     run(
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
agixt-1140-beta-backend-1            |     server.run()
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
agixt-1140-beta-backend-1            |     return asyncio.run(self.serve(sockets=sockets))
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
agixt-1140-beta-backend-1            |     return loop.run_until_complete(main)
agixt-1140-beta-backend-1            |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
agixt-1140-beta-backend-1            |     config.load()
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
agixt-1140-beta-backend-1            |     self.loaded_app = import_from_string(self.app)
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
agixt-1140-beta-backend-1            |     module = importlib.import_module(module_str)
agixt-1140-beta-backend-1            |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-1140-beta-backend-1            |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-1140-beta-backend-1            |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-1140-beta-backend-1            |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-1140-beta-backend-1            |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-1140-beta-backend-1            |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-1140-beta-backend-1            |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-1140-beta-backend-1            |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-1140-beta-backend-1            |   File "/app/app.py", line 18, in <module>
agixt-1140-beta-backend-1            |     with open(os.path.join(this_directory, "src/agent-llm/version"), encoding="utf-8") as f:
agixt-1140-beta-backend-1            | FileNotFoundError: [Errno 2] No such file or directory: '/app/src/agent-llm/version'
agixt-1140-beta-backend-1 exited with code 1

### Steps to Reproduce the Bug

Follow steps in description please.

### Expected Behavior

It should run Agent-LLM like it does on the same machine with v1.3.0 (although older version has network connection issue)

### Actual Behavior

Please read description, has all details. thanks

### Additional Context / Screenshots

![Agent LLM issue](https://github.com/Josh-XT/Agent-LLM/assets/38707551/1e767ff6-1903-4938-9652-5d85a44f7ac5)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of Agent-LLM.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please pull latest and try again, this should be fixed now.

**Comment by mindwellsolutions** [comment]
Thank you. So appreciated!
