### ISSUE TITLE
Running AGiXT v1.1.42 Error: "Pull access denied, repository does not exist or may require 'docker login'"

### ISSUE THREAD

**Issue by mindwellsolutions** [Josh-XT/AGiXT#389]
### Description

This is the first build where I've seen this error, all of the other builds are able to run the backend processes at the start of docker compose all up. My guess is this might have something to do with the renaming of the platform to AGiXT and its call to joshxt/agixt-streamlit having issues as part of transition?

Error: 
docker compose --profile all up
[+] Running 2/2
 ✘ backend Error                                                                                                                                                       0.6s 
 ✘ backend-streamlit Error                                                                                                                                             0.6s 
Error response from daemon: pull access denied for joshxt/agixt-streamlit, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### Steps to Reproduce the Bug

See description

### Expected Behavior

See description

### Actual Behavior

See description

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Should be fixed now, the docker build wasn't finished building yet.
