### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by mirek190** [Josh-XT/AGiXT#390]
### Description

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### Steps to Reproduce the Bug

F:\LLAMA\AGIXT>git clone https://github.com/Josh-XT/AGiXT
Cloning into 'AGiXT'...
remote: Enumerating objects: 4430, done.
remote: Counting objects: 100% (719/719), done.
remote: Compressing objects: 100% (323/323), done.
remote: Total 4430 (delta 422), reused 633 (delta 370), pack-reused 3711
Receiving objects: 100% (4430/4430), 1.39 MiB | 985.00 KiB/s, done.
Resolving deltas: 100% (2749/2749), done.

F:\LLAMA\AGIXT>cd AGiXT

F:\LLAMA\AGIXT\AGiXT>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### Expected Behavior

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### Actual Behavior

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### Additional Context / Screenshots

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Updated docs, sorry forgot to fix that one after things moved.

```
git clone https://github.com/Josh-XT/AGiXT
cd AGiXT/src/agixt
pip install -r requirements.txt
python app.py
```

**Comment by mirek190** [comment]
Thanks
