### ISSUE TITLE
 ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by mindwellsolutions** [Josh-XT/AGiXT#395]
### Description

Thank you, really appreciate helping resolve these issues on the fly! Your last fix removed the /src/ folder error, but it looks like it ran into an issue calling Chain.py. Excited to test this out :)

**Brief Error:**
"agixt-backend-1 | File "/app/app.py", line 9, in
agixt-backend-1 | from Chain import Chain
agixt-backend-1 | File "/app/Chain.py", line 3, in
agixt-backend-1 | from . import AGiXT
agixt-backend-1 | ImportError: attempted relative import with no known parent package"

**Full Error:**
agixt-frontend-1 | ready - started server on 0.0.0.0:3000, url: http://localhost:3000/
agixt-backend-1 | Traceback (most recent call last):
agixt-backend-1 | File "/usr/local/bin/uvicorn", line 8, in
agixt-backend-1 | sys.exit(main())
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in call
agixt-backend-1 | return self.main(*args, **kwargs)
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
agixt-backend-1 | rv = self.invoke(ctx)
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
agixt-backend-1 | return ctx.invoke(self.callback, **ctx.params)
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
agixt-backend-1 | return __callback(*args, **kwargs)
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
agixt-backend-1 | run(
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
agixt-backend-1 | server.run()
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
agixt-backend-1 | return asyncio.run(self.serve(sockets=sockets))
agixt-backend-1 | File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
agixt-backend-1 | return loop.run_until_complete(main)
agixt-backend-1 | File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
agixt-backend-1 | config.load()
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
agixt-backend-1 | self.loaded_app = import_from_string(self.app)
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
agixt-backend-1 | raise exc from None
agixt-backend-1 | File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
agixt-backend-1 | module = importlib.import_module(module_str)
agixt-backend-1 | File "/usr/local/lib/python3.10/importlib/init.py", line 126, in import_module
agixt-backend-1 | return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-1 | File "", line 1050, in _gcd_import
agixt-backend-1 | File "", line 1027, in _find_and_load
agixt-backend-1 | File "", line 1006, in _find_and_load_unlocked
agixt-backend-1 | File "", line 688, in _load_unlocked
agixt-backend-1 | File "", line 883, in exec_module
agixt-backend-1 | File "", line 241, in _call_with_frames_removed
agixt-backend-1 | File "/app/app.py", line 9, in
agixt-backend-1 | from Chain import Chain
agixt-backend-1 | File "/app/Chain.py", line 3, in
agixt-backend-1 | from . import AGiXT
agixt-backend-1 | ImportError: attempted relative import with no known parent package
agixt-backend-1 exited with code 1

### Steps to Reproduce the Bug

See description

### Expected Behavior

See description

### Actual Behavior

See description

### Additional Context / Screenshots

See description

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello, I fixed this one around the same time the issue was made, please pull the latest and give it another shot.

Thanks!
