### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by mindwellsolutions** [Josh-XT/AGiXT#403]
### Description

Hi my apologies for posting a few bug updates in a row, just wanted to help notify you of the errors I'm still getting on my end with install. Ty for the help.

I'm still getting the "ImportError: attempted relative import with no known parent package" with newest build [v1.1.48-beta].

**Brief Error:**
agixt-backend-1            |   File "/app/app.py", line 9, in <module>
agixt-backend-1            |     from Chain import Chain
agixt-backend-1            |   File "/app/Chain.py", line 3, in <module>
agixt-backend-1            |     from . import AGiXT
agixt-backend-1            | ImportError: attempted relative import with no known parent package
agixt-backend-1 exited with code 1

**Full Error:**
docker compose --profile all up
[+] Running 3/0
 ✔ Container agixt-backend-1            Created                                                                                                            0.0s 
 ✔ Container agixt-frontend-1           Created                                                                                                            0.0s 
 ✔ Container agixt-backend-streamlit-1  Created                                                                                                            0.0s 
Attaching to agixt-backend-1, agixt-backend-streamlit-1, agixt-frontend-1
agixt-frontend-1           | yarn run v1.22.19
agixt-frontend-1           | $ next start
agixt-frontend-1           | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  | Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  |   You can now view your Streamlit app in your browser.
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  |   Network URL: http://172.23.0.2:8501
agixt-backend-streamlit-1  |   External URL: http://68.226.89.181:8501
agixt-backend-streamlit-1  | 
agixt-backend-1            | Traceback (most recent call last):
agixt-backend-1            |   File "/usr/local/bin/uvicorn", line 8, in <module>
agixt-backend-1            |     sys.exit(main())
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
agixt-backend-1            |     return self.main(*args, **kwargs)
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
agixt-backend-1            |     rv = self.invoke(ctx)
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
agixt-backend-1            |     return ctx.invoke(self.callback, **ctx.params)
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
agixt-backend-1            |     return __callback(*args, **kwargs)
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
agixt-backend-1            |     run(
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
agixt-backend-1            |     server.run()
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
agixt-backend-1            |     return asyncio.run(self.serve(sockets=sockets))
agixt-backend-1            |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
agixt-backend-1            |     return loop.run_until_complete(main)
agixt-backend-1            |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
agixt-backend-1            |     config.load()
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
agixt-backend-1            |     self.loaded_app = import_from_string(self.app)
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
agixt-backend-1            |     raise exc from None
agixt-backend-1            |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
agixt-backend-1            |     module = importlib.import_module(module_str)
agixt-backend-1            |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-1            |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-1            |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-1            |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-1            |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-1            |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-1            |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-1            |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-1            |   File "/app/app.py", line 9, in <module>
agixt-backend-1            |     from Chain import Chain
agixt-backend-1            |   File "/app/Chain.py", line 3, in <module>
agixt-backend-1            |     from . import AGiXT
agixt-backend-1            | ImportError: attempted relative import with no known parent package
agixt-backend-1 exited with code 1

### Steps to Reproduce the Bug

Check description

### Expected Behavior

Check description

### Actual Behavior

Check description

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello, it appears that your docker container has cached old files.  That code has been changed that it references.  Try this:

```
docker compose down
docker compose build
docker compose --profile all up
```

**Comment by mindwellsolutions** [comment]
Hi Josh. Always appreciated, you're the best! I deleted all previous containers for AgentLLM and AGiXT and followed your steps:
docker compose down
docker compose build
docker compose --profile all up

Unfortunately, I still get the same error. I am confirmed running version v1.1.49-beta:

agixt-backend-1            |   File "/app/app.py", line 9, in <module>
agixt-backend-1            |     from Chain import Chain
agixt-backend-1            |   File "/app/Chain.py", line 3, in <module>
agixt-backend-1            |     from . import AGiXT
agixt-backend-1            | ImportError: attempted relative import with no known parent package
agixt-backend-1 exited with code 1

**Comment by Josh-XT** [comment]
You may need to purge your docker images for it.
