### ISSUE TITLE
Pause Button For Tasks

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#408]
### Problem Description

When Google Bard gets a Rate limit or maybe different api from a different provider receives a rate limit this poses an issue.

### Proposed Solution

Adding a pause button to save all the work in a folder so that when the rate limit has been reset you can have the agent go back and finish its work instead of having the agent do all the tasks again.

### Alternatives Considered

I could have used other providers but if someone didn't have a beefy system to run other providers or don't in general want to run other specific providers.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
The ability to load tasks has been added. Now any time you stop a task, it will save a file with the last status to reference on loading later. Stopping a task is essentially pausing it.
