### ISSUE TITLE
Error loading agent configuration: 'discord_commands' object has no attribute 'PREFIX'

### ISSUE THREAD

**Issue by WillTryToDoItRight** [Josh-XT/AGiXT#418]
### Description

After creating my first agent, and going to chat, I then go back to the settings, I received an error

[Discord is not set up!]

### Steps to Reproduce the Bug

1. create agent
2. go to chat
3. go to settings
4. see error

### Expected Behavior

get the settings of the agent

### Actual Behavior

![image](https://github.com/Josh-XT/AGiXT/assets/131436772/3d523913-bd8d-459d-8790-416268c4eb74)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Updated fix to main, ty.
