### ISSUE TITLE
Error updating agent: 

### ISSUE THREAD

**Issue by WillTryToDoItRight** [Josh-XT/AGiXT#419]
### Description

On the settings page: 
When pushing update agent button I get an error

Got also this error, when creating a new agent with azure as provider

### Steps to Reproduce the Bug

1. got to settings page
2. click 'update agent' button
3. receive error

V2: create agent
1. go to settings page
2. select new agent
3. add details for azure API key
4. select commands (read file, write file, append file, searx search)

### Expected Behavior

get access to the edit entry fields.

### Actual Behavior

![image](https://github.com/Josh-XT/AGiXT/assets/131436772/34ad894a-f081-48ef-91f0-4febc53a8988)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
You may need to clear your commands in your json file for your agent, but this should be fixed now as well.
