### ISSUE TITLE
Error updating agent: name 'available_commands' is not defined

### ISSUE THREAD

**Issue by WillTryToDoItRight** [Josh-XT/AGiXT#423]
### Description

Error updating agent: name 'available_commands' is not defined

For openai and azure as providers.

### Steps to Reproduce the Bug

1. go to settings
2. click on previously added agent
3. (get previously created error)
4. when I click 'update agent' 
5. get new error

### Expected Behavior

can change the settings

### Actual Behavior

![image](https://github.com/Josh-XT/AGiXT/assets/131436772/baebafa8-1651-46d3-bc33-a77127643dc4)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Are these new or existing agents?

**Comment by WillTryToDoItRight** [comment]
existing agents

**Comment by Josh-XT** [comment]
Try with a new agent. It may have old settings that were removed for commands in the current settings file.

**Comment by WillTryToDoItRight** [comment]
now old agents work as well.
