### ISSUE TITLE
LoginFailure: Improper token has been passed.

### ISSUE THREAD

**Issue by WillTryToDoItRight** [Josh-XT/AGiXT#426]
### Description

When I create a new agent with gpt4free, with create file, append file, edit file and searx and then go to chat and type in 'test'
I get an error

same happens when I go to 'instructions'

### Steps to Reproduce the Bug

1. create gpt4free agent
2. add commands
3. go to chat
4. type 'test' 
5. get error

### Expected Behavior

get an response

### Actual Behavior

![image](https://github.com/Josh-XT/AGiXT/assets/131436772/c92d4149-823a-4225-aa24-76330d2f6a6d)

### Additional Context / Screenshots

![image](https://github.com/Josh-XT/AGiXT/assets/131436772/10708bf0-4eca-4c5d-8283-12390b162f7b)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Just pushed an update that should fix this.  It was trying to initialize discord when there wasn't a key.
