### ISSUE TITLE
Move auto restart to dev profile

### ISSUE THREAD

**Issue by localagi** [Josh-XT/AGiXT#429]
### Description

Idk if we really want autorestart on normal profile. Thats where dev profile is meant for @derkahless , please check

https://github.com/Josh-XT/AGiXT/pull/425

If we should move it to the other profile.

@Josh-XT might be a good idea to let me also review the PRs regarding docker - one users feature could break another users expectations. And tbh i can't keep up this way. Need a day for review and test.

In the basic mode, docker containers should follow a certain behaviour to not confuse users.

### Steps to Reproduce the Bug

see https://github.com/Josh-XT/AGiXT/pull/425

### Expected Behavior

Dunno - maybe @derkahless can tell which is the idea behind the autorestart....

### Actual Behavior

Dunno - autorestart was added with no exact desc why

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Not having this setting seemed like an oversight and is for bettering the user experience by restarting the app if it crashes instead of forcing users to go manually restart it. Am I understanding correctly? If so, any reason this should be changed?

**Comment by derkahless** [comment]
In my opinion its better to have. BUT there is a chance to be trapped in a loop somehow if the container is crashing everytime and docker is trying to restart it.

**Comment by localagi** [comment]
> Not having this setting seemed like an oversight and is for bettering the user experience by restarting the app if it crashes instead of forcing users to go manually restart it. Am I understanding correctly? If so, any reason this should be changed?

There is different restart strategies. The correct one should be picked for dev and running and prod envs (last one is out of scope for here)
