### ISSUE TITLE
OSError while starting new task

### ISSUE THREAD

**Issue by ostix360** [Josh-XT/AGiXT#430]
### Description

When I start a new Task with a very long description I have this error` OSError: [Errno 36] File name too long`
I think this is because when we create a new task a file is created with the name of the description and window or WSL2 or docker I don't really know don't like very long file name

### Steps to Reproduce the Bug

Go to the task tab and enter a long description

### Expected Behavior

start the task

### Actual Behavior

crash and don't start the task

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by ven-ven-ven** [comment]
Your task is saved as a .txt file, and the OS has a character limit. The solution for this is to upload the core of the task as a txt file via the upload file option. Make sure you're using the Streamlit frontend (in the agixt folder: steamlit run Main.py). As of writing this tasks are in the middle of a rework so keep your eyes peeled for commits.

**Comment by ostix360** [comment]
Ok thanks for the tips
