### ISSUE TITLE
Docker Streamlit  'ImageNotFound'

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#445]
### Description

When you try to add agent an error will show reading 
```
Error adding agent: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.10/site-packages/docker/errors.py)
```

### Steps to Reproduce the Bug

1. Go to Agent Settings
2. Add Agent
3. Error will appear

### Expected Behavior

When clicking on the add agent it should add the agent with no error and bring up the agent settings to be able to customize the agent.

### Actual Behavior

It shows this error 
```
Error adding agent: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.10/site-packages/docker/errors.py)
```

### Additional Context / Screenshots

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/f7b8e118-2799-4957-8857-fa8cba8f013c)

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [X] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by kenwaytis** [comment]
me2

**Comment by iamsuperzb** [comment]
+1

**Comment by SeattleUser0** [comment]
+2... worked fine three days ago on May 20. Pulled the latest tonight.

**Comment by 0xR4ndom** [comment]
+3 for me too

**Comment by kenfink** [comment]
+4

**Comment by RaiBP** [comment]
+5

**Comment by lgwacker** [comment]
Pull and build the image again. Should be ok.

**Comment by Josh-XT** [comment]
This is fixed, please pull the latest.
