### ISSUE TITLE
 Streamlit Tasks status broken and start

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#451]
### Description

 when you hit start task it starts the task but it doesn't update status it will run you can see on the logs and then a few seconds later it will stop all tasks and it will show running on the status but the stop button is not present.

### Steps to Reproduce the Bug

1.go to tasks
2.write a description on what you want the agent to do for task.
3.the status will not change and will not show running 
3.check logs it will stop the task
4.go back to the tasks it will say running but it the agent will be stopped

### Expected Behavior

Agent to run tasks without stopping and the status of the tasks to show correctly 

### Actual Behavior

Tasks not running but stopping after you start it and tasks status is broken so you can't stop it either.

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [X] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Fixed in #455

**Comment by greengeckowizard** [comment]
> Fixed in #455

its not fixed 😮‍💨

**Comment by greengeckowizard** [comment]
#460 😛
