### ISSUE TITLE
Pull access denied to josh-xt/agixt repository

### ISSUE THREAD

**Issue by jasgeo75** [Josh-XT/AGiXT#452]
### Description

When running docker compose to bring up the containers, the following error occurs:

Error response from daemon: pull access denied for josh-xt/agixt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### Steps to Reproduce the Bug

git clone the repo
docker compose --profile streamlit up

+] Running 1/1
 ✘ backend-streamlit Error                                                                                                                                 2.1s 
Error response from daemon: pull access denied for josh-xt/agixt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### Expected Behavior

expected to be able to pull and run the images necessary to run the app

### Actual Behavior

access denied to you github image registry

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by jasgeo75** [comment]
Fixed it. In your `docker-compose.yaml`  you need to change:

`image: josh-xt/agixt:main` to  ` image: joshxt/agixt:main`

**Comment by jasgeo75** [comment]
Nah, still errors:
`Error adding agent: cannot import name 'ImageNotFound' from 'docker.errors' (/usr/local/lib/python3.10/site-packages/docker/errors.py)`

**Comment by Josh-XT** [comment]
Please try again, the build just finished.

https://github.com/Josh-XT/AGiXT/actions/runs/5062071815

**Comment by Josh-XT** [comment]
`main` build is still running but should finish soon.
https://github.com/Josh-XT/AGiXT/actions/runs/5062070647

**Comment by Josh-XT** [comment]
Build just finished.

**Comment by jasgeo75** [comment]
Error response from daemon: manifest for joshxt/agixt:v1.1.69-beta not found: manifest unknown: manifest unknown

**Comment by jasgeo75** [comment]
Ok, the problem was twofold:

1) The wrong registry name in docker-compose.yml 
2)  If specifying an image version, you need to omit the 'v' in front, so `1.1.69-beta` instead of `v1.1.69-beta`

Seems ok now!

**Comment by Josh-XT** [comment]
> Ok, the problem was twofold:
> 
> 1. The wrong registry name in docker-compose.yml
> 2. If specifying an image version, you need to omit the 'v' in front, so `1.1.69-beta` instead of `v1.1.69-beta`
> 
> Seems ok now!

Thanks!  Just updated the files.  It uses main for now in the compose file due to how frequent changes are happening.  We will version it later.
