### ISSUE TITLE
Streamlit doesn't register checkbox selections sometimes

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#453]
### Description

I've noticed streamlit graying out the screen if you want to select a bunch of agent settings on the checkboxes 
and if you do that it doesn't register sometimes so you gotta go back and recheck the box
the only way rn is just to wait until the grayed is done to prevent it not saving 

### Steps to Reproduce the Bug

1.Go to Agent settings
2.Check the boxes really fast
3.Problem is there grayed out and sometimes it doesn't register right away.

### Expected Behavior

you should be able to check really fast without having it to save as you keep checking instead it should be saving when you click the update agent settings so it will save as once instead of continuous on the agent settings.

### Actual Behavior

It keeps saving continuous so it doesn't allow you to save all quickly.

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [X] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
[https://cdn.discordapp.com/attachments/1097720481970397358/1110950206255681606/VideoCrop_20230524_101803769.mp4](url)

**Comment by Josh-XT** [comment]
Fixed issue by making agent settings a form.
