### ISSUE TITLE
Streamlit Agent Selection Doesn't update on the right side

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#454]
### Description

When you select the agent in the list on the left sidebar it doesn't update the selection on the right side in the agent settings page so it can be very confusing when you want to make a change to the agent settings.

### Steps to Reproduce the Bug

1.select agent settings
2.select agent in left box the one you want to make a change settings to.
3.It won't update on the right when you select on agent from left.

### Expected Behavior

when you select the agent on the left it should update on the right so you can make changes to it.

### Actual Behavior

Currently when you select the agent on the left the one you want to make settings change to it it doesn't register and change on the right.

### Additional Context / Screenshots

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/4515ba1e-0aba-4a21-898c-e1468f98864a)

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [X] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Fixed in#455
