### ISSUE TITLE
Tasks issue when accessing task

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#458]
### Description

Gives error when trying to access tasks 

File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/ubuntu/AGiXT/agixt/pages/4-Tasks.py", line 22, in <module>
    existing_tasks = task_agent.get_tasks_files()
File "/home/ubuntu/AGiXT/agixt/Tasks.py", line 92, in get_tasks_files
    files = os.listdir(os.path.join("agents", self.agent_name, "tasks"))

### Steps to Reproduce the Bug

1. Go create  agent any provider
2. Go to tasks
3. Error will show

### Expected Behavior

It should not show error 

### Actual Behavior

Shows error. 
File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/ubuntu/AGiXT/agixt/pages/4-Tasks.py", line 22, in <module>
    existing_tasks = task_agent.get_tasks_files()
File "/home/ubuntu/AGiXT/agixt/Tasks.py", line 92, in get_tasks_files
    files = os.listdir(os.path.join("agents", self.agent_name, "tasks"))

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [X] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [X] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by derkahless** [comment]
Problem was fixed with commit #bf08aaa

**Comment by greengeckowizard** [comment]
> Problem was fixed with commit #bf08aaa
> 
> can be closed, i suppose

My bad sorry I thought you were commenting on the another issue for the tasks status. Yeah it seems like it's fixed.
