### ISSUE TITLE
Privacy enhancements

### ISSUE THREAD

**Issue by localagi** [Josh-XT/AGiXT#459]
### Problem Description

Following dependencies are known to call home:

- https://docs.trychroma.com/telemetry
- streamlit

### Proposed Solution

For Chroma, opt out as mentioned https://docs.trychroma.com/telemetry

For streamlit, add a button in the browser to js-wise disable the logging from within the browser

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
Streamlit problems will be moving to the Streamlit repo soon.  I will look into ways to disable the Streamlit telemetry.
