### ISSUE TITLE
Requirements.txt Updates

### ISSUE THREAD

**Issue by Josh-XT** [Josh-XT/AGiXT#462]
### Problem Description

We're being negatively impacted by module versions being forced by other modules we're using and by other modules introducing breaking changes with function/class name changes.

### Proposed Solution

We need to update our `requirements.txt` to force known working versions with our software.

### Alternatives Considered

Yelling at everyone else doing this or making breaking changes to their modules.  Seems like a waste of time though.

### Additional Context

- gpt4free forcing the Streamlit version has broken things for some people.
- DuckDuckGo search updating their module had breaking changes with all functions and class names changed which required code changes in order to restore functionality.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by mongolu** [comment]
Chill man, you're not in production!

**Comment by localagi** [comment]
> Chill man, you're not in production!

Partly, it's me. I want to run it, and it randomly breaks bc of dependencies. Not because of non-working code.
This takes a lot of time - each single time to find out if the error is in source or not.
Just trying to find a solution. Happy for guidance :)

**Comment by mirek190** [comment]
Maybe search function and read text shouldn't use some web pages api? 
Maybe is some framework or ready application which will be digest data from web pages without special apis?

**Comment by Josh-XT** [comment]
> Maybe search function and read text shouldn't use some web pages api? Maybe is some framework or ready application which will be digest data from web pages without special apis? That will give you more Independence from api providers .

You kind of have to pick your battles when building stuff like this.  There is always the possibility that I could write any of the modules that I'm using better than the people who wrote them, but there isn't the possibility of me having the time to do so.  Happy to take suggestions of other modules to use.  We have several search modules available to use, DuckDuckGo is just the default for the sake of privacy and it being free without requiring an API key.  You can also use Google's official API or Searx, but they're just additional setup for API keys that no one wants to really do.

**Comment by mirek190** [comment]
I was thinking something like this one   ;)

https://stackoverflow.com/questions/1141136/how-can-i-programmatically-perform-a-search-without-using-an-api

To be independent from API

**Comment by Josh-XT** [comment]
Lots has changed on the internet since 2009, most websites have safeguards against you doing these things now.



Josh Throckmorton | DevXT<https://devxt.com/>

Chief Technology Officer

***@***.******@***.***>

________________________________

**Comment by mirek190** [comment]
Have you seen this one 

https://selenium-python.readthedocs.io

Selenium is a project that helps you to automate web browsers. 
You can use it to test web applications or do other tasks that involve interacting with web pages.
