### ISSUE TITLE
ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)

### ISSUE THREAD

**Issue by DIGist** [Josh-XT/AGiXT#466]
### Description

Just pulled a new docker container and am trying to run the container and get this runtime error:

ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)

### Steps to Reproduce the Bug

docker compose --profile all pull

docker compose --profile streamlit up

watch log

### Expected Behavior

No error

### Actual Behavior

> 2023-05-25 23:12:55.343 Uncaught app exception
> agixt-backend-streamlit-1  | Traceback (most recent call last):
> agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
> agixt-backend-streamlit-1  |     exec(code, module.__dict__)
> agixt-backend-streamlit-1  |   File "/agixt/pages/2-Chat.py", line 2, in <module>
> agixt-backend-streamlit-1  |     from AGiXT import AGiXT
> agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 10, in <module>
> agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
> agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Mandraw** [comment]
Yup same thing outside of docker in app.py :
`$ python app.py
2023-05-26 03:52:00.020016: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2023-05-26 03:52:00.020072: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Traceback (most recent call last):
  File "D:\Tools\AGiXT\agixt\app.py", line 6, in <module>
    from AGiXT import AGiXT
  File "D:\Tools\AGiXT\agixt\AGiXT.py", line 11, in <module>
    from duckduckgo_search import DDGS
ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (D:\Tools\Miniconda\lib\site-packages\duckduckgo_search\__init__.py)
`
AND in the streamlit calls to create a new agent ( dunno if it's just because it's trying to launch app.py ? )
`Error adding agent: cannot import name 'DDGS' from 'duckduckgo_search' (D:\Tools\Miniconda\lib\site-packages\duckduckgo_search_init_.py)`

**Comment by Pyvos** [comment]
Been said, but here is a comprehensive log:
(agentllm) PS C:\Users\deV\source_code\repos\AGiXT\agixt> docker compose --profile streamlit up
[+] Running 10/10
 ✔ backend-streamlit 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                             49.2s 
   ✔ f03b40093957 Already exists                                                                                                                                              0.0s 
   ✔ 05c2151a829c Already exists                                                                                                                                              0.0s 
   ✔ 94970648c551 Already exists                                                                                                                                              0.0s 
   ✔ cf2e0f30894f Already exists                                                                                                                                              0.0s 
   ✔ 661be8ca6397 Already exists                                                                                                                                              0.0s 
   ✔ e0e56f943cbb Pull complete                                                                                                                                              16.3s 
   ✔ 346006aea2de Pull complete                                                                                                                                              16.3s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                              16.4s 
   ✔ 322f35b526a9 Pull complete                                                                                                                                              43.0s 
[+] Running 2/2
 ✔ Network agixt_default                Created                                                                                                                               0.0s 
 ✔ Container agixt-backend-streamlit-1  Created                                                                                                                               0.6s 
Attaching to agixt-backend-streamlit-1
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  | Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  |   You can now view your Streamlit app in your browser.
agixt-backend-streamlit-1  | 
agixt-backend-streamlit-1  |   Network URL: http://172.19.0.2:8501
agixt-backend-streamlit-1  |   External URL: http://68.12.112.186:8501
agixt-backend-streamlit-1  |
agixt-backend-streamlit-1  | 2023-05-26 03:33:31.940 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/4-Tasks.py", line 2, in <module>
agixt-backend-streamlit-1  |     from Tasks import Tasks
agixt-backend-streamlit-1  |   File "/agixt/Tasks.py", line 1, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:33:35.325 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/3-Instructions.py", line 2, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:33:36.531 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/2-Chat.py", line 2, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:33:43.636 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/Main.py", line 12, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:26.387 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:28.263 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:29.630 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:30.344 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:30.713 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:30.882 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:31.052 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)
agixt-backend-streamlit-1  | 2023-05-26 03:34:33.260 Uncaught app exception
agixt-backend-streamlit-1  | Traceback (most recent call last):
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
agixt-backend-streamlit-1  |     exec(code, module.__dict__)
agixt-backend-streamlit-1  |   File "/agixt/pages/0-Agent_Settings.py", line 13, in <module>
agixt-backend-streamlit-1  |     agent_name, agent = agent_selector()
agixt-backend-streamlit-1  |   File "/agixt/components/agent_selector.py", line 45, in agent_selector
agixt-backend-streamlit-1  |     agent = Agent(selected_agent)
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 20, in __init__
agixt-backend-streamlit-1  |     self.commands = self.load_commands()
agixt-backend-streamlit-1  |   File "/agixt/Agent.py", line 126, in load_commands
agixt-backend-streamlit-1  |     module = importlib.import_module(f"commands.{module_name}")
agixt-backend-streamlit-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
agixt-backend-streamlit-1  |     return _bootstrap._gcd_import(name[level:], package, level)
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
agixt-backend-streamlit-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
agixt-backend-streamlit-1  |   File "/agixt/commands/create_new_command.py", line 4, in <module>
agixt-backend-streamlit-1  |     from AGiXT import AGiXT
agixt-backend-streamlit-1  |   File "/agixt/AGiXT.py", line 11, in <module>
agixt-backend-streamlit-1  |     from duckduckgo_search import DDGS
agixt-backend-streamlit-1  | ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)

**Comment by ychy00001** [comment]
code changed, docker image python requirement not update

**Comment by vmajor** [comment]
Can confirm. Broken for me too:
`ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/site-packages/duckduckgo_search/__init__.py)`

**Comment by derkahless** [comment]
Broken on non Docker Version too.

`
 http://192.168.0.27:85012023-05-26 14:08:10.926 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/data/Zwei/AI_TESTS/AGiXT/agixt/Main.py", line 12, in <module>
    agent_name, agent = agent_selector()
  File "/data/Zwei/AI_TESTS/AGiXT/agixt/components/agent_selector.py", line 45, in agent_selector
    agent = Agent(selected_agent)
  File "/data/Zwei/AI_TESTS/AGiXT/agixt/Agent.py", line 20, in __init__
    self.commands = self.load_commands()
  File "/data/Zwei/AI_TESTS/AGiXT/agixt/Agent.py", line 126, in load_commands
    module = importlib.import_module(f"commands.{module_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/Zwei/AI_TESTS/AGiXT/agixt/commands/create_new_command.py", line 4, in <module>
    from AGiXT import AGiXT
  File "/data/Zwei/AI_TESTS/AGiXT/agixt/AGiXT.py", line 11, in <module>
    from duckduckgo_search import DDGS
ImportError: cannot import name 'DDGS' from 'duckduckgo_search' (/usr/local/lib/python3.10/dist-packages/duckduckgo_search/__init__.py)

`

**Comment by Josh-XT** [comment]
Yes, `duckduckgo_search` module made breaking changes to their class names, so I had to modify all that code.  Once you upgrade your `duckduckgo_search` module, this will be resolved.
