### ISSUE TITLE
TASK AGENT - ends prematurly with "All tasks completed or stopped."

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#468]
### Description

give task `Write the text 'Happy birthday, Mihai!' into a text file named 'Happy.txt'`
agent provider oobabooga, max tokens `1500`, temperature `0.7`, model type `vicuna`
it runs 2 cycles and stops like it's finished.

### Steps to Reproduce the Bug

create agent with provider `oobabooga`, max tokens `1500`, temp `0.7`, type `vicuna`

in text-generation-webuit start 
`python server.py --model-dir ~/LLMmodels --listen --threads 12 --extensions api openai --cpu --mlock --chat --n_batch 512 --no-cache --disk-cache-dir /mnt/e/temp/ --verbose --model a_CRD716_ggml-vicuna-1.1-quantized --load-in-4bit --quant_type nf4`

in webpage http://[localhost:3000/agent/xxx](http://localhost:3000/agent/xxx) give task `Write the text 'Happy birthday, Mihai!' into a text file named 'Happy.txt'`

### Expected Behavior

to continue execution or to throw an error at some point

### Actual Behavior

after cycle 2 it ends loop

### Additional Context / Screenshots

![image](https://github.com/Josh-XT/AGiXT/assets/5344119/e503358d-c117-4ef8-9ef2-2c798a699989)
- also, in ui it doesn't refresh anything.
- and no commands are shown in right tab (i manually edited the config.json in agent's directory and replaced false with true)

This is the first response:
```
Primary Objective: Write the text 'Happy birthday, Mihai!' into a text file named 'Happy.txt'

Task:
```
Break down the objective into a list of small achievable tasks in the form of instructions that lead up to achieving the ultimate goal of the objective. Make use of available COMMANDS.
```

Task Response:
```

First, let's create a new file called Happy.txt and open it with the write_file command.
```python
open_file = commands.write_file("Happy.txt", "Text to be added")
```
Next, we will use the read_file command to get the text that is already in the file, so we can add our new text to it.
```swift
read_file_output = commands.read_file(open_file)
```
Now we have the existing text in the file, let's concatenate our new text to it using the append_to_file command.
```python
concat_text = "Happy birthday, Mihai!"
new_text = commands.append_to_file(open_file, concat_text)
```
Finally, we will use the read_file command again to make sure our new text is in the file and write the Happy.txt file with all the text in it using the write_file command.
```python
read_file_output = commands.read_file(open_file)
write_file_output = commands.write_file("Happy.txt", read_file_output)
```
```

You are a command execution agent.  If there are no commands, respond only with empty Json like {}. If there are commands to use from the Task Response, format them as follows in your response:

```
{
    "commands": {
        "command_name": {
            "arg1": "val1",
            "arg2": "val2"
        },
        "command_name2": {
            "arg1": "val1",
            "arg2": "val2",
            "argN": "valN"
        }
    }
}
```
--------------------
```

This is the second:
```
Primary Objective: Write the text 'Happy birthday, Mihai!' into a text file named 'Happy.txt'

Task:
```
Break down the objective into a list of small achievable tasks in the form of instructions that lead up to achieving the ultimate goal of the objective. Make use of available COMMANDS.
```

Task Response:
```

First, let's create a new file called Happy.txt using the `create_command` command.
```python
+---------------------------------------------------+
|                                                   |
|               TASK LIST                             |
|                                                   |
+---------------------------------------------------+
|1. create_command                                      |
|---------------------------------------------------|
|Task: Create a new file called Happy.txt using the     |
|`create_command` command.                           |
|---------------------------------------------------|
|### Commands Available To Complete Task:          |
|* create_command                                      |
|---------------------------------------------------|
```
Next, let's write 'Happy birthday, Mihai!' into the Happy.txt file using the `write_to_file` command.
```python
+---------------------------------------------------+
|                                                   |
|               TASK LIST                             |
|                                                   |
+---------------------------------------------------+
|2. write_to_file                                      |
|---------------------------------------------------|
|Task: Write 'Happy birthday, Mihai!' into the Happy.txt  |
|file using the `write_to_file` command.              |
|---------------------------------------------------|
|### Commands Available To Complete Task:          |
|* write_to_file                                       |
|---------------------------------------------------|
```
Finally, let's use the `scrape_text_with_selenium` command to scrape some text from a website that has birthday wishes for Mihai.
```python
+---------------------------------------------------+
|                                                   |
|               TASK LIST                             |
|                                                   |
+---------------------------------------------------+
|3. scrape_text_with_selenium                          |
|---------------------------------------------------|
|Task: Use the `scrape_text_with_selenium` command to     |
|scrape some text from a website that has birthday        |
|wishes for Mihai.                                      |
|---------------------------------------------------|
|### Commands Available To Complete Task:          |
|* scrape_text_with_selenium                           |
|---------------------------------------------------|
```
```

You are a command execution agent.  If there are no commands, respond only with empty Json like {}. If there are commands to use from the Task Response, format them as follows in your response:

```
{
    "commands": {
        "command_name": {
            "arg1": "val1",
            "arg2": "val2"
        },
        "command_name2": {
            "arg1": "val1",
            "arg2": "val2",
            "argN": "valN"
        }
    }
}
```
--------------------
```

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
NextJS front end is broken, please use the Streamlit one.  Issues related to the NextJS front end should be directed to the Front End repo. https://github.com/JamesonRGrieve/Agent-LLM-Frontend
