### ISSUE TITLE
Support huggingface endpoints

### ISSUE THREAD

**Issue by localagi** [Josh-XT/AGiXT#475]
### Problem Description

Models like starchat-alpha are just a bit too big to work with - locally and free version on huggingchat.

Deploying an endpoint would help, but we dont have a connector?

I think this would be the easiest way...
https://huggingface.co/docs/api-inference/detailed_parameters#conversational-task

### Proposed Solution

Add a provider for huggingface endpoints. 

I've got a key ready for share when to be tested.

### Additional Context

Endpoint https://cmwl8xarfldzr1sv.us-east-1.aws.endpoints.huggingface.cloud

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
Added `huggingface` provider but have not tested yet, just followed their API documentation.  Feel free to give it a shot.
