### ISSUE TITLE
No  Arm64 images Docker

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#484]
### Description

When installing docker install the entry for Arm64 is removed.

### Steps to Reproduce the Bug

Run ```docker compose --profile streamlit up```
will show 
```no matching manifest for linux/arm64/v8 in the manifest list entries```

### Expected Behavior

Supposed to install from pull arm64 build on docker

### Actual Behavior

```no matching manifest for linux/arm64/v8 in the manifest list entries```
![image](https://github.com/Josh-XT/AGiXT/assets/34012548/fa0ff57f-aed3-44c8-b4b1-c2932b6be1ed)

### Additional Context / Screenshots

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/19dbbde9-ba1f-430c-bd4a-6fa75661b52d)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
All you gotta do is just uncomment this line 
![image](https://github.com/Josh-XT/AGiXT/assets/34012548/e57e9f44-aa61-4f36-ab6b-fba46134885b)

@Josh-XT @localagi

**Comment by localagi** [comment]
@greengeckowizard yes, we experienced further issues. Currently, also on local install, it installs due to our declared version for pytorch is not available on arm.

So the Q is at @Josh-XT - which torch version should we use? 1.13.1 seems avail on arm64. Non-cpu 2.0.1 probably also - will it work? is it worth a try?

**Comment by localagi** [comment]
https://github.com/Josh-XT/AGiXT/blob/707afda53bf618d0fa9cb5335ba08e0eaf9f4817/pyproject.toml#L93

https://github.com/Josh-XT/AGiXT/blob/707afda53bf618d0fa9cb5335ba08e0eaf9f4817/pyproject.toml#L77

**Comment by localagi** [comment]
Dendencies using it 

https://github.com/Josh-XT/AGiXT/blob/707afda53bf618d0fa9cb5335ba08e0eaf9f4817/poetry.lock#LL5108C1-L5108C1

https://github.com/Josh-XT/AGiXT/blob/707afda53bf618d0fa9cb5335ba08e0eaf9f4817/poetry.lock#L4546

https://github.com/Josh-XT/AGiXT/blob/707afda53bf618d0fa9cb5335ba08e0eaf9f4817/poetry.lock#L19

**Comment by Josh-XT** [comment]
> @greengeckowizard yes, we experienced further issues. Currently, also on local install, it installs due to our declared version for pytorch is not available on arm.
> 
> So the Q is at @Josh-XT - which torch version should we use? 1.13.1 seems avail on arm64. Non-cpu 2.0.1 probably also - will it work? is it worth a try?

I'm not sure, I don't directly use torch.  It is used by `sentence-transformers` which is used by ChromaDB for our default embedding models.

**Comment by localagi** [comment]
@greengeckowizard Please check the latest builds if they work for you

**Comment by greengeckowizard** [comment]
> @greengeckowizard Please check the latest builds if they work for you

Sure I can give it a quick test but rn I see the docker status is failing idk if that will do anything.

**Comment by greengeckowizard** [comment]
> @greengeckowizard Please check the latest builds if they work for you

Awesome just tested and it works although the docker failing we'll have to look into in the github page thanks for your work!! I can now close this issue.  @localagi
