### ISSUE TITLE
Make getting steps endpoint work

### ISSUE THREAD

**Issue by localagi** [Josh-XT/AGiXT#495]
### Description

Focussing just on few endpoints, i think there is more related to chains, but starting with a simple workflow:
- create chain
- create step
- get steps

### Steps to Reproduce the Bug

![image](https://github.com/Josh-XT/AGiXT/assets/132956819/8c643a27-a966-4c51-bba0-7b5ef431e87c)
![image](https://github.com/Josh-XT/AGiXT/assets/132956819/53e8bb1e-5fd7-4efb-8cc1-1e59d7c045aa)
![image](https://github.com/Josh-XT/AGiXT/assets/132956819/7be08b3f-57e6-4547-9779-a155d6d1cfec)

### Expected Behavior

I get and see the step created

### Actual Behavior

Method not allowed (happening on other step endpoints also, e.g. PUT update a step)

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by localagi** [comment]
@Josh-XT tell me if we drop this endpoint. 

"Get all steps from a chain" would return a list of steps with all their details.

We have already:

"Get a chain" - which returns a chain and a list of all embedded steps with all their details (please confirm "all their details")

So we won't need it anymore? (I would check app.py and remove if stubs left)

**Comment by Josh-XT** [comment]
Resolved.
