### ISSUE TITLE
Streamlit Tasks status broken

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#500]
### Description

This is the same issue as this I don't think I have to explain this issue again #460

### Steps to Reproduce the Bug

Go to tasks and start it 

### Expected Behavior

Show if the agent is running or stopped and completed the task

### Actual Behavior

Doesn't update the status of the agent

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [X] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [X] Remote

### Environment Type - Container

- [X] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
Here's some instructions to fix this issue https://app.cognosys.ai/s/fXNR960 feel free anyone to test with these suggested fixes.

**Comment by Josh-XT** [comment]
Tasks converted to chain, no longer relevant.
