### ISSUE TITLE
 [Documentation] Add this in documentation

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#509]
### Problem Description

No problem but simply can make it easier for others incase they have the same question.

### Proposed Solution

adding "if you make a field empty that has a forced default, it'll come back to the default" on the documentation when you edit/add the agent settings in streamlit

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by localagi** [comment]
@greengeckowizard Good idea, maybe even have a handbook with screenshots? If you could do someting like this to /docs/handbook - that'd be great!

**Comment by greengeckowizard** [comment]
> 

Also very good idea 👍
