### ISSUE TITLE
Make chain steps move again

### ISSUE THREAD

**Issue by localagi** [Josh-XT/AGiXT#518]
### Description

The whole chain step creation, adding, changing and especially moving needs some reviev

- it doesn't matter which step number i put in when creating a step. It is appended to the end.
- I cant move steps - the endpoint is just missing
- i cant't git all steps from a chain - the endpoint is missing

- this is weirdest - GET chain after repeatedly adding steps to place 1 and 2
```

{'chain': {'chain_name': 'test_quickcheck_chain',
           'steps': [{'agent_name': 'instruction',
                      'prompt': 'test_quickcheck_agent',
                      'prompt_type': 'What is the capital of France?',
                      'step': 1},
                     {'agent_name': 'instruction',
                      'prompt': 'test_quickcheck_agent',
                      'prompt_type': 'What is the capital of Spain?',
                      'step': 2},
                     {'agent_name': 'instruction',
                      'prompt': 'test_quickcheck_agent',
                      'prompt_type': 'What is the capital of France?',
                      'step': 1},
                     {'agent_name': 'instruction',
                      'prompt': 'test_quickcheck_agent',
                      'prompt_type': 'What is the capital of France?',
                      'step': 1}]}}
```

### Steps to Reproduce the Bug

Current main source

### Expected Behavior

Normal CRUD behaviour

### Actual Behavior

wild!

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
#555 should fix maybe.

**Comment by localagi** [comment]
Tests be fixed in https://github.com/Josh-XT/AGiXT/pull/562

**Comment by Josh-XT** [comment]
Resolved.
