### ISSUE TITLE
Need a clear example to use streamlit for tasks, chain with example prompt

### ISSUE THREAD

**Issue by pearlmary** [Josh-XT/AGiXT#522]
### What piece of documentation is affected?

Need an example each for task, chat, chain etc. to work on streamlit. 

### What part(s) of the article would you like to see updated?

examples in streamlit (samples)

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by pearlmary** [comment]
Also, with the new git clone today, in streamlit the main is not working
![image](https://github.com/Josh-XT/AGiXT/assets/29123795/85f314af-90a8-4b31-814e-7c50a95ac3f2)

**Comment by Josh-XT** [comment]
> ### What piece of documentation is affected?
> Need an example each for task, chat, chain etc. to work on streamlit.
> 
> ### What part(s) of the article would you like to see updated?
> examples in streamlit (samples)
> 
> ### Additional Information
> _No response_
> 
> ### Acknowledgements
> * [x]  My issue title is concise, descriptive, and in title casing.
> * [x]  I have searched the existing issues to make sure this feature has not been requested yet.
> * [x]  I have provided enough information for the maintainers to understand and evaluate this request.

The documentation that we do have can be found here: https://josh-xt.github.io/AGiXT/

I would recommend giving the core concepts a good read over to get a better idea of what these features do and their purposes. I've also added another chain for writing a poem and saving it to a file in the latest version to help give an example.  

Top priority has been working through the issues as they come up and making high value improvements to the software.  Anyone is welcome to contribute better documentation or examples.

**Comment by mr-september** [comment]
> Anyone is welcome to contribute better documentation or examples.

Nobody can contribute if nobody can figure out how to make this work at all. There having absolutely 0 youtube videos showing/mentioning/clickbaiting AGiXT in ANY way should be a huge red flag on the state of accessibility.

**Comment by Josh-XT** [comment]
> > Anyone is welcome to contribute better documentation or examples.
> 
> Nobody can contribute if nobody can figure out how to make this work at all. There having absolutely 0 youtube videos showing/mentioning/clickbaiting AGiXT in ANY way should be a huge red flag on the state of accessibility.

People have been contributing, some people are able to go read our documentation to understand the program, if that is insufficient, understand that this is a one man show where I get the help from a few people here and there. Sponsorships to increase the amount of time I'm able to spend on the project would help here. I'm a software engineer, not a video creator or documentation expert. I suggested contributions because that is not my wheel house.

**Comment by Josh-XT** [comment]
> > Anyone is welcome to contribute better documentation or examples.
> 
> Nobody can contribute if nobody can figure out how to make this work at all. There having absolutely 0 youtube videos showing/mentioning/clickbaiting AGiXT in ANY way should be a huge red flag on the state of accessibility.

Also, no one is forcing anyone's hand. If you see it as a red flag and can't go read the code, then it may just not be for you.
