### ISSUE TITLE
[Poetry] Include install FFMPEG and or AVCONV

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#530]
### What piece of documentation is affected?

The installation aspect of it. 
![image](https://github.com/Josh-XT/AGiXT/assets/34012548/915e5f57-f7ea-408e-a5ac-e8c01f80827c)

### What part(s) of the article would you like to see updated?

This should include the needed steps to resolve this error or a change in the poetry code to make it work 

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
Any particular version that you're aware of or just the latest of those?
