### ISSUE TITLE
Streamlit - Add console output for Tasks

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#532]
### Problem Description

Well to be able to see the action you got to view the logs in the device that you are hosting from. This is an issue as the multi user setup won't be able to remote into the host machine.

### Proposed Solution

have a console output so that any user can see the console output ONLY their agent and user should be able the see their outputs only not other users.

### Alternatives Considered

This is idea is inspired by cognosys where they have the logs being showed as the agent runs through.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by foolsh** [comment]
+1 This would improve the experience quite a bit, took me a minute to realize it was doing work in the background and not just stalled.

I'd suggest not sending the whole log, maybe just grep it for the "Task:" it's working on at the moment, like..

`Task: Add the following code to the `hello.py` file using the `write_to_file` command:`

**Comment by localagi** [comment]
I don't see multi-user nor multi-tenant capability anywhere near future. Just a login won't do there is a lot more of caveats.
And from business architectural point of view, I won't go this approach. Too expensive in time and money. Too worthless in terms of revenue.

If the goal is to serve multiple users, every user just gets his/her own instance. 
Better to offer a service to "host your own AGiXT in one click".

**Comment by localagi** [comment]
However, i see a value in some download button to download ALL logs, so a user can put the logs to a ticket with ease.

**Comment by localagi** [comment]
If you like to improve the logging in any manner, we have an open task: Put named loggers onto all our loggings
https://www.techmagic.co/blog/top-serverless-platforms/

Currently we are logging INFO on root logger, and that will get messy soon (async haha, you can't track anything anymore in the logs)

**Comment by Josh-XT** [comment]
Task converted to a chain, no longer relevant.
