### ISSUE TITLE
Add sharable links to the agent outputs 

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#533]
### Problem Description

Well this isn't really an issue but it would be nice to have sharable links like the cognosys program.

### Proposed Solution

Having sharable links means that if you were working in a large work setting you can easily share its outputs to co-workers etc.. even this can help in development as you can share directly to other contributors to try to view what it had instead of trying to share complete screenshots etc... 

### Additional Context

This is simply an idea inspired by cognosys

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by Josh-XT** [comment]
I'll think of an good way to implement, but in the short term, each agent will have a `history.yaml` file in their agent folder which contains the interaction history with that agent.

**Comment by Josh-XT** [comment]
Added exports.
