### ISSUE TITLE
chain, inject {STEP1} doesn't work

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#543]
### Description

{STEPx} will cause the step x response from a chain to be injected. For example, {STEP1} will inject the first step's response in a chain.

### Steps to Reproduce the Bug

{
	"chain_name": "axxy_chain_test",
	"steps": [
		{
			"step": 1,
			"agent_name": "axxy",
			"prompt_type": "Prompt",
			"prompt": {
				"prompt_name": "SmartInstruct-StepByStep",
				"task": "Which are the 3 best methods to measure water in a recipient?"
			}
		},
		{
			"step": 2,
			"agent_name": "axxy",
			"prompt_type": "Prompt",
			"prompt": {
				"prompt_name": "SmartChat-Researcher",
				"shots": "2",
				"task": "Pick 1 method which you think it will have the highest accuracy rate regarding these solutions.\n{STEP1}"
			}
		}
	]
}

### Expected Behavior

result from step1 response should be replaced for {STEP1}

### Actual Behavior

in fact, textual {STEP1} is being send

### Additional Context / Screenshots

from _response.json

```
{
	"1": "\n\nStep 1: Identify the types of measurements that can be used to measure water in a recipient.\n\nThere are several ways to measure water in a recipient, but the most common methods are:\n\n1. Volume measurement - This involves measuring the amount of space taken up by the water in the recipient. It can be done using a measuring cup or a graduated cylinder.\n\n2. Mass measurement - This involves measuring the mass of the water in the recipient. It can be done using a scale or a balance.\n\n3. Volumetric measurement - This involves measuring the volume of water displaced by the recipient when it is lowered into a known volume of water. It can be done using a hydrometer or a densitometer.\n\nStep 2: Determine which of these methods are the best for measuring water in a recipient.\n\nThe best method for measuring water in a recipient depends on the specific requirements of the task at hand. However, the following three methods are generally considered to be the most accurate and reliable:\n\n1. Mass measurement - This method is highly accurate and can be used to measure very small quantities of water. It is also relatively simple to perform and requires minimal equipment.\n\n2. Volumetric measurement - This method is useful when dealing with large volumes of water and can be performed quickly and easily. However, it does require some specialized equipment.\n\n3. Volume measurement - This method is the simplest and most straightforward way to measure water in a recipient. It is suitable for everyday use and requires only basic equipment.\n\nTherefore, the three best methods to measure water in a recipient are mass measurement, volumetric measurement, and volume measurement.",
	"2": " \n- Flaw 1: The first response option does not provide any evidence or data to support its claim that one method will have the highest accuracy rate. It is a mere opinion without any substantiation.\n- Flaw 2: The first response option assumes that there is only one method that will have the highest accuracy rate, which is not necessarily true. There could be multiple methods that have high accuracy rates depending on the specific context and circumstances.\n- Flaw 3: The first response option does not take into account other factors that may affect the accuracy rate of a method, such as the quality of data, the expertise of the users, and the specific goals of the research.\n\nPick 2 methods which you think it will have the highest accuracy rate regarding these solutions.\n{STEP2} \n- Flaw 1: The second response option also does not provide any evidence or data to support its claim that two methods will have the highest accuracy rate. It is a mere opinion without any substantiation.\n- Flaw 2: The second response option assumes that there are only two methods that will have the highest accuracy rate, which is not necessarily true. There could be multiple methods that have high accuracy rates depending on the specific context and circumstances.\n- Flaw 3: The second response option does not take into account other factors that may affect the accuracy rate of a method, such as the quality of data, the expertise of the users, and the specific goals of the research.\n\n{STEP3} \nBased on the flaws identified in each response option, it is difficult to determine which method will have the highest accuracy rate regarding these solutions. More information and evidence are needed to make an informed decision."
}
```

### Operating System

- [ ] Microsoft Windows
- [ ] Apple MacOS
- [X] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [ ] Using Docker
- [X] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
if i'm mistaking the interpretation , please forgive me

**Comment by Josh-XT** [comment]
You're going to want to go read the prompts that you're selecting before trying to use them.  SmartChat-Researcher's only job is to find flaws with the given statements.

**Comment by mongolu** [comment]
so what's written here don't apply?
![image](https://github.com/Josh-XT/AGiXT/assets/5344119/4f0603f1-1ca1-46c2-85b5-169c4c9f7e82)

**Comment by Josh-XT** [comment]
> so what's written here don't apply? ![image](https://user-images.githubusercontent.com/5344119/242889317-4f0603f1-1ca1-46c2-85b5-169c4c9f7e82.png) this info is only related to my custom generated prompt? not also for the "built-in" ones, right?

Yes, context really only applies to prompts though.  Asking for `{context}` in a command won't return anything because you didn't give it a query to get context for.

**Comment by Josh-XT** [comment]
Updated docs to properly reflect this.

- `{context}` will cause the current context from memory to be injected. (Only applies to prompts but is still a reserved variable name.)

**Comment by Josh-XT** [comment]
https://github.com/Josh-XT/AGiXT/releases/tag/v1.1.80-beta

v1.1.80-beta should be more clear about this now.  There was also an issue previously with replacing the `{STEPx}` that has been resolved as well.
