### ISSUE TITLE
ERROR IN EXECUTION_AGENT & file creation in tasks / instructions not working

### ISSUE THREAD

**Issue by daouid** [Josh-XT/AGiXT#561]
### Description

Agents called via the Instructions & Tasks are not able to write files to workspace.

ERROR IN EXECUTION_AGENT

Files creation tested using the "write a poem" chain, AGiXT is able to access and write files to the WORKSPACE as expected.

### Steps to Reproduce the Bug

1. Go to /instructions page
2. Give this simple instruction "I want you to create an empty txt file in your workspace  called "my_file.txt""
3. Docker terminal output:
Your task: I want you to create an empty txt file in your workspace  called "my_file.txt"
2023-06-04 11:48:27,277 | INFO | [GPT4Free] Using: DeepAI
2023-06-04 11:48:28,457 | INFO | Failed to use DeepAI: 401 Client Error: Unauthorized for url: https://api.deepai.org/chat_response
2023-06-04 11:48:28,458 | INFO | [GPT4Free] Using: You
2023-06-04 11:48:31,180 | INFO | 
ERROR IN EXECUTION_AGENT, validated_response:
2023-06-04 11:48:31,180 | INFO | {'response': 'File creation successful.', 'commands': {'write_to_file': {'filename': 'my_file.txt', 'text': ''}}}
2023-06-04 11:48:31,180 | INFO | Response: File creation successful.
Commands Executed:
{'write_to_file': {'filename': 'my_file.txt', 'text': ''}}
Command Execution Response:
No commands were executed.

5. No my_file.txt in workspace

### Expected Behavior

Command should be ran and the file created

### Actual Behavior

The agent only describe how to make a file, but does not actually do the job

### Additional Context / Screenshots

Using brave browser on windows 10

### Operating System

- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Linux
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local
- [ ] Remote

### Environment Type - Container

- [X] Using Docker
- [ ] Not Using Docker

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
I believe I fixed this today, let me know if still having an issue.

https://github.com/Josh-XT/AGiXT/commit/11b99f69bcff5ab3984acc0f4dde92956e87668d

**Comment by daouid** [comment]
Still the same error:
![image](https://github.com/Josh-XT/AGiXT/assets/20565034/dd1d24a6-24ab-446d-8041-6885c30a221b)

**Comment by Josh-XT** [comment]
> Still the same error: ![image](https://user-images.githubusercontent.com/20565034/243763866-dd1d24a6-24ab-446d-8041-6885c30a221b.png)

This appears to be because of how the AI responded, it didn't respond in the correct format that it was told to do for the command execution.  It appears to have failed to validate the response.

**Comment by daouid** [comment]
Can confirm that via latest commit I could write an empty test file using both "instructions" & "tasks" modes
