### ISSUE TITLE
Vercel deployment

### ISSUE THREAD

**Issue by johnfelipe** [Josh-XT/AGiXT#589]
### Feature/Improvement Description

Vercel deployment button

### Proposed Solution

Vercel deployment button
And
Readme.md with instructions 

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Docs are at https://agixt.com and in our readme.  I am not sure if we can deploy the back end to Vercel or not, I am not very familiar with their services yet.
