### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by johnfelipe** [Josh-XT/AGiXT#597]
### Description

	agixt-agixt-1  | Traceback (most recent call last):
	agixt-agixt-1  |   File "/root/.cache/pypoetry/virtualenvs/agixt-VV6BEKu2-py3.10/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
	agixt-agixt-1  |     exec(code, module.__dict__)
	agixt-agixt-1  |   File "/agixt/agixt/pages/5-Instructions.py", line 18, in <module>
	agixt-agixt-1  |     agent_name = agent_selector()
	agixt-agixt-1  |   File "/agixt/agixt/components/agent_selector.py", line 19, in agent_selector
	agixt-agixt-1  |     agent_names = [agent["name"] for agent in ApiClient.get_agents()]
	agixt-agixt-1  |   File "/agixt/agixt/ApiClient.py", line 65, in get_agents
	agixt-agixt-1  |     response = requests.get(f"{base_uri}/api/agent")
	agixt-agixt-1  |   File "/root/.cache/pypoetry/virtualenvs/agixt-VV6BEKu2-py3.10/lib/python3.10/site-packages/requests/api.py", line 73, in get
	agixt-agixt-1  |     return request("get", url, params=params, **kwargs)
	agixt-agixt-1  |   File "/root/.cache/pypoetry/virtualenvs/agixt-VV6BEKu2-py3.10/lib/python3.10/site-packages/requests/api.py", line 59, in request
	agixt-agixt-1  |     return session.request(method=method, url=url, **kwargs)
	agixt-agixt-1  |   File "/root/.cache/pypoetry/virtualenvs/agixt-VV6BEKu2-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
	agixt-agixt-1  |     resp = self.send(prep, **send_kwargs)
	agixt-agixt-1  |   File "/root/.cache/pypoetry/virtualenvs/agixt-VV6BEKu2-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
	agixt-agixt-1  |     r = adapter.send(request, **kwargs)
	agixt-agixt-1  |   File "/root/.cache/pypoetry/virtualenvs/agixt-VV6BEKu2-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
	agixt-agixt-1  |     raise ConnectionError(e, request=request)
	agixt-agixt-1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=7437): Max retries exceeded with url: /api/agent (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2acdbdd030>: Failed to establish a new connection: [Errno 111] Connection refused'))

### Steps to Reproduce the Bug

	git clone https://github.com/Josh-XT/AGiXT

	cd AGiXT && docker compose up

### Expected Behavior

connect with ip:port

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using poetry
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Back sure the container for your backend is up.

**Comment by johnfelipe** [comment]
Pls send me md file or commands for test I'm in Ubuntu 20

**Comment by Josh-XT** [comment]
https://github.com/Josh-XT/AGiXT/blob/main/agixt/tests.ipynb

**Comment by Josh-XT** [comment]
https://github.com/Josh-XT/AGiXT/blob/main/AGiXT.sh

This may also help get started.

**Comment by WackyZet** [comment]
get same error once，run “docker compose pull“，then retry “docker compose up”，get this error fixed
guess docker image has been modified

**Comment by Josh-XT** [comment]
https://josh-xt.github.io/AGiXT/1-Getting%20started/Quick%20Start.html

Please see the latest Quickstart guides, things seem working currently.
