### ISSUE TITLE
I use Macbook M1 the docker image is not support my system.

### ISSUE THREAD

**Issue by jirayudech** [Josh-XT/AGiXT#60]
% docker compose up -d
[+] Running 0/2
 ⠴ backend Pulling                                                                                                                                                    2.4s 
 ⠴ frontend Pulling                                                                                                                                                   2.4s 
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by bigr00** [comment]
To get it to work on M1, then we have to change the Docker Compose file to build the images locally, not fetch them from Github.
Also, we have to change the Dockerfile-backend to this:
`FROM --platform=linux/arm64 python:3.10-slim-buster AS base`

docker-compose.yml:
`version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URI: http://backend:5000
    env_file:
      - .env
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
`

**Comment by bigr00** [comment]
Seems that building the Docker images gets stuck at this step:

>  => [base  7/12] RUN pip install --no-cache-dir -r requirements.txt                                                 114.9s
>  => => #       [end of output]
>  => => #   note: This error originates from a subprocess, and is likely not a problem with pip.
>  => => #   ERROR: Failed building wheel for pyllamacpp
>  => => #   Building wheel for duckdb (setup.py): started
>  => => #   Building wheel for duckdb (setup.py): still running...

**Comment by Josh-XT** [comment]
> Seems that building the Docker images gets stuck at this step:
> 
> > => [base  7/12] RUN pip install --no-cache-dir -r requirements.txt                                                 114.9s
> > => => #       [end of output]
> > => => #   note: This error originates from a subprocess, and is likely not a problem with pip.
> > => => #   ERROR: Failed building wheel for pyllamacpp
> > => => #   Building wheel for duckdb (setup.py): started
> > => => #   Building wheel for duckdb (setup.py): still running...

Looks like pyllamacpp may not work on Mac? I don't see why it wouldn't or why docker would operate differently in Mac than Linux.

**Comment by bigr00** [comment]
After removing pyllamaccp and deleting the Python file, it finally builds.

**Comment by bigr00** [comment]
There seems to be a clash in Mac with the 5000 port as well for backend.

**Comment by Josh-XT** [comment]
Please see https://github.com/Josh-XT/Agent-LLM/pull/67 and pull the latest.

**Comment by Josh-XT** [comment]
If you've already tried running with docker-compose, you may need to do the following after pulling latest changes:

```
docker-compose down
docker-compose -f docker-compose-mac.yml down
```

Then do:

```
docker-compose -f docker-compose-mac.yml up --build -d
```

**Comment by Josh-XT** [comment]
Please continue this conversation in #61 - we have some more information over there and there is a lot of overlap with this issue.
