### ISSUE TITLE
url for demo before try install locally

### ISSUE THREAD

**Issue by johnfelipe** [Josh-XT/AGiXT#601]
### Feature/Improvement Description

put a url with demo for try

### Proposed Solution

add in md file demo for url or video demostration

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Will continue to track this in #679 as that is where discussion has been happening for this.
