### ISSUE TITLE
error with oobabooga api:IndexError: index -1 is out of bounds for dimension 1 with size 0 

### ISSUE THREAD

**Issue by WackyZet** [Josh-XT/AGiXT#609]
### Description

i'm failed to intergrate oobabooga api,got this error:
INFO | FORMATTED PROMPT: None.
agixt in docker get this null response: agixt-agixt-1  | | INFO | Response: 

and i checked oobabooga,got this error :  
"POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/opt/llama-text-generation-webui/modules/text_generation.py", line 249, in generate_reply_HF
    output = shared.model.generate(**generate_params)[0]
  File "/home/anaconda3/envs/oobabooga/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/oobabooga/lib/python3.10/site-packages/transformers/generation/utils.py", line 1312, in generate
    and torch.sum(inputs_tensor[:, -1] == generation_config.pad_token_id) > 0
IndexError: index -1 is out of bounds for dimension 1 with size 0
Output generated in 0.02 seconds (0.00 tokens/s, 0 tokens, context 0, seed 960775490)

then I test oobabooga api,it works fine ：
"POST /api/v1/generate HTTP/1.1" 200 -
Output generated in 33.09 seconds (7.55 tokens/s, 250 tokens, context 17, seed 1337128703)

i have checked the uri i‘m using，it's set to docker0 ip:  http://172.17.0.1:5000

### Steps to Reproduce the Bug

start agixt with docker compose up,
use chat to send a message

### Expected Behavior

get a nomal response

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using poetry
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by WackyZet** [comment]
seems aint about network ，using agixt to send chat message via api， oobabooga recieved post request already，but throwed errors，
meanwhile，if sending same message via api with api format following oobabooga  exsample，it works just fine without any error，
so it maybe something wrong with agixt 's  oobabooga api format？

**Comment by Josh-XT** [comment]
Sorry I think I misread the error earlier. I haven't tried ooba in awhile, do you have their latest version?

**Comment by WackyZet** [comment]
got it solved ，nothing wrong with python code，set max_tokens too large ,my bad
didn't realize it till debugging oobabooga.py

**Comment by Josh-XT** [comment]
Awesome, glad you figured it out.  Thanks for updating us!
