### ISSUE TITLE
script AGiXT.sh asks for root permission

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#629]
### Description

When I run it, it does his thing and I think sudo apt update and upgrade is issued somewhere, but not in the script itself, maybe in the poetry actions.

### Steps to Reproduce the Bug

run the script from a non root user

### Expected Behavior

not to do that

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using poetry
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
```
sudo: 3 incorrect password attempts
Failed to install browsers
```

**Comment by mongolu** [comment]
no, why should i do this? i believed it was "sufficient" a simple user account, why need sudo?
also, if smth needs to be run as su, it must be specified in docs, else one cannot trust the script (one=me)
maybe thiis browser installs could be done in another way?

**Comment by Josh-XT** [comment]
It needs permission to install playwright and its browsers.

**Comment by Josh-XT** [comment]
Admin rights likely necessary for running, nothing I can do about this.
