### ISSUE TITLE
OpenAI API Compatible Endpoints for each Agent (with optional additional arguements)

### ISSUE THREAD

**Issue by kenfink** [Josh-XT/AGiXT#643]
### Feature/Improvement Description

So much new dev now is using OpenAI API compatibility.  Every time there's a new demo CoLab Notebook for a paper, it simply wants an OpenAI Key and can usually accept an OPEN_AI_BASE or openai.api_base endpoint.  

AGiXT's backend really shines as a "one-ring-to-rule-them-all" solution - there's already support for so many diverse providers and the ability to set each agent to use a different provider and with different prompts and settings.  And it's already set up to be a FastAPI server.  

A way to point that Notebook/Langchain/Code at an endpoint for a particular agent in AGiXT (localhost:7437/api/agent/{agent_name}/v1 would be a game-changer.  It would allow use of the same server or docker-image for a half-dozen LLMs, some proxied like revChatGPT (with different model settings, prompts etc), and some local specialized LLMs (ie Gorilla), all handled by one server, ideally with parallel workers for each agent.

That way when the next camel, tree-of-thoughts, fun-new-langchain-experiment comes along, I can simply point it at different agents on a single AGiXT server, each with its own endpoint.

Today's post from the FastChat folks summarizes the point here nicely:
https://lmsys.org/blog/2023-06-09-api-server/

### Proposed Solution

Update [app.py](https://github.com/Josh-XT/AGiXT/blob/main/agixt/app.py) to include [OpenAI API Endpoints.](https://platform.openai.com/docs/models/model-endpoint-compatibility)

Specifically /v1/chat/completions, /v1/completions, /v1/embeddings endpoints to each agent.

For example, currently an agent can be reached at /api/agent/{agent_name}/chat

Add 
/api/agent/{agent_name}/v1/chat/completions
/api/agent/{agent_name}/v1/completions
/api/agent/{agent_name}/v1/embeddings

And check that the JSONs/payloads returned are in line with what's spec-ed out at https://platform.openai.com/docs/api-reference

This has been done for individual engines and proxies, for example:
https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md
https://github.com/acheong08/ChatGPT-to-API
https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by kenfink** [comment]
Here's where FastChat made the magic happen: https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/openai_api_server.py

Might be a good template?

**Comment by Josh-XT** [comment]
Thanks for the great suggestion - I am planning to work on this, I just haven't had time yet.  There are some challenges to get past to be able to do this well, such as adding the ability to override agent settings if things like temperature are in the API post.  

Making the endpoints to accept whatever args and just throw them away except the ones it needs is an alternative approach that I could implement sooner then improve on later.

**Comment by kenfink** [comment]
> Making the endpoints to accept whatever args and just throw them away except the ones it needs is an alternative approach that I could implement sooner then improve on later.

I'd be all for that.   Setting settings at agent level seems not only reasonable but possibly a better call.  Each agent might have different settings and thus a different response to the same call.  Plus easier/faster.

Big additional request is to include (optional) function calling in the API and just throw it away if it's not relevant to that agent's endpoint.  I'm really hoping we can figure out LoRAs to port this to local LLMs soon, and having that structure in place would be wonderful, so design a prototype workflow with OpenAI Function calling now, and easily move it to a specialized LLM once it exists.

**Comment by kenfink** [comment]
Thinking about this one step further - instead of (or in addition to) /api/agent/{agent_name}/v1/chat/completions, etc, could we use a single API Endpoint but have the API Key or Model Name indicate which agent to use?

So for example if it all went to /openedapi/v1/chat/completions, and if the Model started with "Agent:"
"Agent:AgentName,ModelName" then it would route to the right agent, and the agent would throw away / overwrite ModelName (for now, maybe pass it later?)  Come to think of it, it might even be simplest for now to just use the Model string as the Agent Calling name, and let the agent take care of the rest.

I wonder if this might make it even easier to route clients, since Model Name choice seems to be a ubiquitous thing in everyone's protypes.  Point once, then change the model name in each call.  

Would this be easier to implement with a single redirect endpoint and make model= the agent identifier?

**Comment by Josh-XT** [comment]
Merged #731 , give it a try and let me know if there is anything that needs changed with it.

**Comment by Josh-XT** [comment]
I haven't added to override any agent settings but it will at least pass through and give you the same kind of response you'd expect from OpenAI endpoints.

**Comment by kenfink** [comment]
Yes!!!!!!!

Instead of agent_name, could it be passed through "model"?  That way lanchain etc will know what to do with it.  Model gets thrown away by the agent anyway.

**Comment by Josh-XT** [comment]
Sure I can do that, gimme a few minutes.

**Comment by Josh-XT** [comment]
Updated that in #732
