### ISSUE TITLE
Parallel Agent Workers and Stop Button

### ISSUE THREAD

**Issue by kenfink** [Josh-XT/AGiXT#644]
### Feature/Improvement Description

Each agent and its respective provider can get stuck long inference generation tasks, retry loops, etc...   I don't believe there is currently a way to stop a running agent / provider.  Agent/provider activity can currently create backlogs for any other tasks, including sending stop-task commands.

### Proposed Solution

Spawn each agent and the FastAPI server into their own worker processes.
Add the ability to stop each agent and its respective worker in the backend.  Save memory on stopping.

Add a "stop agent" button to the UI for each agent.

Add a stop-all button to the sidebar.

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Each agent action happens on another asyncio worker now. There is an option to execute chain steps one by one if the desire is there to stop it, otherwise it should be considered like a function that puts prompts, commands, and other chains together.
