### ISSUE TITLE
Error in web app - Interact

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#666]
### Description

Access "Interact", choose "Chains", choose agent, in "Choose a Chain to Run" select "Smart instruct", in "User input" write something.
When press "Perform action" the error is thrown

`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

```
Traceback:
File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/mihai/AGiXT/streamlit/pages/3-Interact.py", line 144, in <module>
    ApiClient.run_chain(chain_name=chain_name, user_input=user_input)
File "/home/mihai/AGiXT/streamlit/ApiClient.py", line 204, in run_chain
    return response.json()
File "/home/mihai/.local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
```

![image](https://github.com/Josh-XT/AGiXT/assets/5344119/2fe69852-3ba5-42cc-9eca-ec36412236c2)

### Steps to Reproduce the Bug

1. Access "Interact"
2. choose "Chains"
3. choose agent
4. "Choose a Chain to Run" select "Smart instruct"
5. in "User input" write something.
6. Press "Perform action"

### Expected Behavior

run w/o error

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [ ] Using poetry
- [X] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
I've deleted local folder AGiXT and did a clean clone, and now it's working.
Don't know what happened, maybe streamlit directory didn't got refreshed?

**Comment by Josh-XT** [comment]
What is the back end console showing when this happens?

**Comment by Josh-XT** [comment]
You may also need to go change the agent in that chain if the issue is related to gpt4free timing out.
