### ISSUE TITLE
[DOCUMENTATION] Video Guides

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#679]
### Feature/Improvement Description

Some people wonder hey does AGiXT have a youtube channel or something well look no further if we have a channel people can learn how to use AGiXT with the awesome guides we create.

### Proposed Solution

Making videos can help people better understand how to use AGiXT. BTW Full credit to this request from @Kiro from the discord server.

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Sounds like a good job for @ven-ven-ven !  My video editing experience is a lot less than thrilling.  I did take a bunch of screenshots earlier though.

https://josh-xt.github.io/AGiXT/1-Getting%20started/Screenshots.html

**Comment by greengeckowizard** [comment]
> Sounds like a good job for @ven-ven-ven ! My video editing experience is a lot less than thrilling. I did take a bunch of screenshots earlier though.
> 
> https://josh-xt.github.io/AGiXT/1-Getting%20started/Screenshots.html

If nobody can do it I can if it comes down to that.

**Comment by pegas07770** [comment]
This is very necessary and important in my opinion.  I understand the logic behind the Josh-XT project.  But I don't understand how to properly configure the project to work with LLM, for example with koboldcpp.  Yes, the documentation https://josh-xt.github.io/AGiXT/ is nice and structured.  But it's not detailed enough in my opinion.  I was unable to set up the interaction between AGiXT and koboldcpp (https://github.com/LostRuins/koboldcpp) using this documentation.  I tried many times.  And I don't understand what I'm doing wrong.  Or it just doesn't work as intended.  It would be interesting to learn as much as possible about the examples of setting up the AGiXT project for working with local large language models.  In video or text format.  It would be great if there would be a detailed FAQ on the project.

**Comment by Josh-XT** [comment]
https://www.youtube.com/watch?v=XbjjPdYRM_k
