### ISSUE TITLE
Describe Image None? Image

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#682]
### Description

When I run the chain with the provided url to the image source it gives error did you mean ```https://None?```

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/1d3d6b00-465a-41f1-91a3-f85d5f4562c1)

### Steps to Reproduce the Bug

Run Chain with 1 Step for Describe Image I used raw JPG file to a website source  you can test with other image types.

### Expected Behavior

Supposed to Give you a description of the image but instead it shows error.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [ ] Using poetry
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Confirmed resolved.
