### ISSUE TITLE
Add Perplexity Ai as provider

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#711]
### Feature/Improvement Description

Adding Perplexity ai allows users to use their perplexity paid account for a provider with AGiXT.

### Proposed Solution

I saw on a discord server this wrapper being posted I think this should be implemented into this project as it can add the provider for perplexity ai

https://github.com/helallao/perplexity-ai

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by ostix360** [comment]
I'm working on it

**Comment by Josh-XT** [comment]
@ostix360 resolved I'm #948
