### ISSUE TITLE
Cannot run local or docker since latest commit

### ISSUE THREAD

**Issue by med4u** [Josh-XT/AGiXT#712]
### Description

Cannot run local or docker since latest commit [0702ecbe037165224e5fce40dcc73155d138d462](https://github.com/Josh-XT/AGiXT/commit/0702ecbe037165224e5fce40dcc73155d138d462)
But does work with "git checkout" the commit before : dab1a163559fc21ae7e8c02399a24a4ff7b070ca

### Steps to Reproduce the Bug

Git pull
./AGiXT.sh shows menu
Option 1 : Step 1, 2, 3 .... then falls back to the menu and nothing started

When I  try with docker it is the same

### Expected Behavior

start backend and frontend

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using poetry
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
Hi I see you checked you're using poetry can you try to git pull with the latest changes since we removed poetry and switched back to requirements.txt you can use the start script called ```AGiXT.sh```

**Comment by med4u** [comment]
Problem solved now with updates to source code between PR 0702ecbe037165224e5fce40dcc73155d138d462 and 056ecb2c54865f2fbd21f5ac2dfd806dc0747c0f
