### ISSUE TITLE
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#717]
### Description

Using Docker running locally not on a vps. 

When you try to send a chat message to the agent it says 

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/86e41a4d-81bf-45bb-99e5-23f8145d4129)

and here's the output log

[message (2).txt](https://github.com/Josh-XT/AGiXT/files/11752962/message.2.txt)

### Steps to Reproduce the Bug

1.Start Docker Container
2.Go to Interact page
3.Send a message 
Error will show

### Expected Behavior

Its supposed to respond with a message for which it does but it conks out and kills out for a second but the backend seems to still be running after it says that.

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/bd2199ab-8038-4045-acc6-f691fb7d8ad0)

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Can you confirm if this is ongoing? I haven't been able to reproduce this morning.

**Comment by kenfink** [comment]
Ongoing.  I see a number of similar posts in Discord with the same issue today, including my updated docker install.

**Comment by Josh-XT** [comment]
It has been a bit, this seems to be working in docker on my phone atm, anyone still having the issue?
