### ISSUE TITLE
i feell a strager's foot into my house

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#728]
### Description

xterm: Xt error: Can't open display: 172.19.192.1:0.0
Get:1 file:/var/cuda-repo-wsl-ubuntu-11-7-local  InRelease [1575 B]
Get:2 file:/var/cudnn-local-repo-ubuntu2004-8.9.1.23  InRelease [1572 B]
Get:1 file:/var/cuda-repo-wsl-ubuntu-11-7-local  InRelease [1575 B]
Get:2 file:/var/cudnn-local-repo-ubuntu2004-8.9.1.23  InRelease [1572 B]
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:8 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Hit:9 https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64  InRelease
Hit:10 https://deb.nodesource.com/node_12.x focal InRelease
Hit:11 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:12 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease
Reading package lists...
xterm: Xt error: Can't open display: 172.19.192.1:0.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package xorg-mkfontscale
E: Unable to locate package xorg-font-utils
E: Unable to locate package tts-ms-fonts
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package xorg-mkfontscale
E: Unable to locate package xorg-font-utils
E: Unable to locate package tts-ms-fonts
Reading package lists...
Building dependency tree...
Reading state information...
xterm is already the newest version (353-1ubuntu1.20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '3.10.12' for 'python' was not found
Reading package lists...
Building dependency tree...
Reading state information...
python3-pip is already the newest version (20.0.2-5ubuntu1.9).
python3.10 is already the newest version (3.10.12-1+focal1).
0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2
xterm: Xt error: Can't open display: 172.19.192.1:0.0
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one
...

See 'git help git' for an overview of the system.
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version (1:2.25.1-1ubuntu3.11).
0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
xterm: Xt error: Can't open display: 172.19.192.1:0.0
Reading package lists...
Building dependency tree...
Reading state information...
dbus-x11 is already the newest version (1.12.16-2ubuntu2.3).
0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
./AGiXT.sh: eval: line 234: unexpected EOF while looking for matching `''
./AGiXT.sh: eval: line 235: syntax error: unexpected end of file
xterm: Xt error: Can't open display: 172.19.192.1:0.0
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/mihai/.local/lib/python3.10/site-packages (23.1.2)
xterm: Xt error: Can't open display: 172.19.192.1:0.0
tail: stat_req_logs.txt: file truncated

==> stat_req_logs.txt <==
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: anthropic==0.2.9 in /home/mihai/.local/lib/python3.10/site-packages (from -r /home/mihai/AGiXT/static-requirements.txt (line 1)) (0.2.9)
Requirement already satisfied: beautifulsoup4==4.12.2 in /home/mihai/.local/lib/python3.10/site-packages (from -r /home/mihai/AGiXT/static-requirements.txt (line 2)) (4.12.2)
...
Requirement already satisfied: pycparser in /home/mihai/.local/lib/python3.10/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub==1.58.2->-r /home/mihai/AGiXT/static-requirements.txt (line 19)) (2.21)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/mihai/.local/lib/python3.10/site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit==1.22.0->-r /home/mihai/AGiXT/static-requirements.txt (line 25)) (0.19.3)
Requirement already satisfied: mdurl~=0.1 in /home/mihai/.local/lib/python3.10/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit==1.22.0->-r /home/mihai/AGiXT/static-requirements.txt (line 25)) (0.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/mihai/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.19.0->google-api-python-client==2.87.0->-r /home/mihai/AGiXT/static-requirements.txt (line 10)) (0.5.0)
Requirement already satisfied: humanfriendly>=9.1 in /home/mihai/.local/lib/python3.10/site-packages (from coloredlogs->onnxruntime>=1.14.1->chromadb==0.3.25->-r /home/mihai/AGiXT/static-requirements.txt (line 4)) (10.0)

==> log.txt <==
xterm: Xt error: Can't open display: 172.19.192.1:0.0
tail: req_logs.txt: file truncated

==> req_logs.txt <==
Defaulting to user installation because normal site-packages is not writeable
Obtaining gpt4free from git+https://github.com/xtekky/gpt4free.git@6d0328c20bb58107a3de4a42054fc048aed2c4ee#egg=gpt4free (from -r /home/mihai/AGiXT/requirements.txt (line 13))
  Skipping because already up-to-date.
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: cryptography==41.0.0 in /home/mihai/.local/lib/python3.10/site-packages (from -r /home/mihai/AGiXT/requirements.txt (line 1)) (41.0.0)
Requirement already satisfied: EdgeGPT==0.6.7 in /home/mihai/.local/lib/python3.10/site-packages (from -r /home/mihai/AGiXT/requirements.txt (line 2)) (0.6.7)
Requirement already satisfied: GoogleBard==1.1.3 in /home/mihai/.local/lib/python3.10/site-packages (from -r /home/mihai/AGiXT/requirements.txt (line 3)) (1.1.3)
...
jinja2->altair<5,>=3.2.0->streamlit<2.0.0,>=1.21.0->gpt4free->-r /home/mihai/AGiXT/requirements.txt (line 13)) (2.1.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/mihai/.local/lib/python3.10/site-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit<2.0.0,>=1.21.0->gpt4free->-r /home/mihai/AGiXT/requirements.txt (line 13)) (0.19.3)
Building wheels for collected packages: gpt4free
  Building editable for gpt4free (pyproject.toml): started
  Building editable for gpt4free (pyproject.toml): finished with status 'done'
  Created wheel for gpt4free: filename=gpt4free-0.1.0-py3-none-any.whl size=18262 sha256=13654a100d66db76148d67ed377ab59d4bdf48b8c45ce3cab0bc8193504c6797
  Stored in directory: /tmp/pip-ephem-wheel-cache-k74fmr5y/wheels/52/02/15/513ca12dacbc7fdb8dce25bbd4d438d8ca7187e98a4b9446e4
Successfully built gpt4free

==> log.txt <==
xterm: Xt error: Can't open display: 172.19.192.1:0.0

==> req_logs.txt <==
Installing collected packages: gpt4free
  Attempting uninstall: gpt4free
    Found existing installation: gpt4free 0.1.0
    Uninstalling gpt4free-0.1.0:
      Successfully uninstalled gpt4free-0.1.0
Successfully installed gpt4free-0.1.0

==> log.txt <==
sudo: playwright: command not found
sudo: playwright: command not found

### Steps to Reproduce the Bug

select 1. Install Locally & Run Streamlit

### Expected Behavior

run without sudo , display things that are happening, local w/o docker, not upgrading pip over my wish, not upgrading system packages over my wish

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Certain packages are required and have to install for it to run properly. If you do not want things to install locally, do not choose local, use docker.
