### ISSUE TITLE
Local llama model not working - for instance Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_1.bin via llama-cpp-python[server]

### ISSUE THREAD

**Issue by mirek190** [Josh-XT/AGiXT#733]
### Description

console output:

USER: hello

{'id': 'cmpl-30ab8a26-9d60-4a60-b1d1-8325826f3da9', 'object': 'text_completion', 'created': 1686935866, 'model': 'F:/LLAMA/AGiXT/agixt/models/Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_1.bin', 'choices': [{'text': '', 'index': 0, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 34, 'completion_tokens': 1, 'total_tokens': 35}}
2023-06-16 18:17:46,329 | INFO | Error: object str can't be used in 'await' expression
2023-06-16 18:17:46,329 | INFO | PROMPT CONTENT: None
You are LOCAL, an expert at answering the users question.  Use available context help answer the users questions.

USER: hello

2023-06-16 18:17:46,329 | INFO | TOKENS: 29
2023-06-16 18:17:46,329 | INFO | Failed to get a response 5 times in a row.
2023-06-16 18:17:46,334 | INFO | Response: None
2023-06-16 18:17:46,334 | INFO | Response: None
2023-06-16 18:17:46,334 | INFO | Response: None
2023-06-16 18:17:46,334 | INFO | Response: None
INFO:     127.0.0.1:12512 - "POST /api/agent/LOCAL/prompt HTTP/1.1" 200 OK

### Steps to Reproduce the Bug

1. run server llama-cpp-python[server] with the model Wizard-Vicuna-7B-Uncensored.ggmlv3.q5_1.bin
2. run AGiXT
3. setup new agent  - Set Select Provider to llamacppapi , Set Select Embedder to llamacpp , Set AI_PROVIDER_URI to http://localhost:8000 ( like llama server shows ) 
4. save it
5. test with chat 

Lllama server getting data from AGIXT

output:

llama_print_timings:        load time =  1992.45 ms
llama_print_timings:      sample time =     0.21 ms /     1 runs   (    0.21 ms per token)
llama_print_timings: prompt eval time =     0.00 ms /     1 tokens (    0.00 ms per token)
llama_print_timings:        eval time =   176.22 ms /     1 runs   (  176.22 ms per token)
llama_print_timings:       total time =   200.36 ms
←[32mINFO←[0m:     ::1:12527 - "←[1mPOST /v1/completions HTTP/1.1←[0m" ←[32m200 OK←[0m

### Expected Behavior

should works?

### Operating System

- [ ] Linux
- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by dominicOT** [comment]
To whoever might make an attempt to fix this error, possible causes could be:

Incorrect or Compatibility Syntax Issue with the 'await' expression and 'str' object.

**Comment by mirek190** [comment]
any help with that issue?

**Comment by Josh-XT** [comment]
Sorry this one was overlooked when doing async changes.  Should be all set now.  Thanks!
