### ISSUE TITLE
Bard research format

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#748]
### Description

Bard puts its outputs differently so when running research it goes in loops.

### Steps to Reproduce the Bug

1.have bard as agent
2.run task chain with research 

### Expected Behavior

Is supposed to complete research with Google Bard

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Modified this last week and forgot to close, we discussed on discord.
