### ISSUE TITLE
TOKENIZERS 

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#751]
### Description

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/6df599ed-e09d-41f7-b960-9b08862d35c8)

### Steps to Reproduce the Bug

Run Tasks

### Expected Behavior

we gotta set this 

For Powershell
```
$env:TOKENIZERS_PARALLELISM = $true
```

and for bash

```
export TOKENIZERS_PARALLELISM=true
```

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
hmm even after pr #757 it still shows error like that

**Comment by Josh-XT** [comment]
Fixed in one of my last PRs
