### ISSUE TITLE
Chain 4 not found Smart Chain Tasks and Research

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#758]
### Description

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/195190de-abbc-4aca-9d06-fe009442642a)

### Steps to Reproduce the Bug

1. Run the smart tasks chain with research 
2. let it get to step 4
3. error will appear

### Expected Behavior

Its supposed to perform whatever step 4 does in the chain for smart task and research. 

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Fixed in #761 and #762
