### ISSUE TITLE
after importing agent with .json KeyError 'chat_history'

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#763]
### Description

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/515b67c3-72b0-4168-84dd-178ed8f84451)

### Steps to Reproduce the Bug

1.Go import agent with .json format from export
2.go to chat
error will show

### Expected Behavior

no error 

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Fixed in #765
