### ISSUE TITLE
Smart Task Chain /w research stops 

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#767]
### Description

After Running the smart task with research it goes through but out of nowhere it just stops and you can give it a few minutes its not doing anything.

### Steps to Reproduce the Bug

1.Run Smart Task chain give it a task input to do and let it run for a few hours

### Expected Behavior

it supposed to not only research but also run the chain with the commands to complete the necessary user input.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by greengeckowizard** [comment]
Turns out this was the path issue its now fixed supposedly

**Comment by greengeckowizard** [comment]
The issue is still occurring while it still stops.

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/874e883c-d24b-45f6-b404-e14bc032147a)

**Comment by Josh-XT** [comment]
If any chain hits an error, it stops.
