### ISSUE TITLE
Running a chain made from smart task without research when running the chain it researches.

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#769]
### Description

When running a chain made from a smart task chain without research you expect it to function the way you think it would function where it doesn't run the chain with research because you absolutely intended it to run with no research.
It still does research which is a problem as if you don't want it to do research then whats the point of having smart task chain without research if when you run the chain its gonna research it anyway.

### Steps to Reproduce the Bug

Generate a chain using smart task chain without research 
and then run that chain it will run with research.

### Expected Behavior

Again as I mentioned in the Description what it should do is not run the chain with research as if you chose the without research it should not run that chain with research since you might want to see what that ai's capabilities without the need for a research.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Should be fixed with #772
