### ISSUE TITLE
truncation length with ooba

### ISSUE THREAD

**Issue by kkuette** [Josh-XT/AGiXT#773]
### Description

TRUNCATION_LENGTH doesnt change 

TRUNCATION_LENGTH = 8192

> agixt_1  | {'prompt': "USER:Today's date is June 20, 2023 09:58 PM. \n\nYou are a web search suggestion agent. Suggest 5 web searches for the task given. Attempt to make suggestions that will ensure top results are recent information and from reputable information sources.\n\nReturn the suggestions in a numbered list with no other comments.\n\nTask: Who is the kkuette ?\nASSISTANT:", 'max_new_tokens': 1931, 'do_sample': True, 'temperature': 0.7, 'top_p': 0.1, 'typical_p': 1.0, 'epsilon_cutoff': 0.0, 'eta_cutoff': 0.0, 'tfs': 1.0, 'top_a': 0.0, 'repetition_penalty': 1.18, 'encoder_repetition_penalty': 1.0, 'top_k': 40, 'min_length': 0.0, 'no_repeat_ngram_size': 0.0, 'num_beams': 1, 'penalty_alpha': 0.0, 'length_penalty': 1.0, 'early_stopping': False, 'mirostat_mode': 0.0, 'mirostat_tau': 5.0, 'mirostat_eta': 0.1, 'seed': -1, 'add_bos_token': True, 'truncation_length': 2048, 'ban_eos_token': False, 'skip_special_tokens': True, 'custom_stopping_strings': '', 'stopping_strings': ['</s>']}

### Steps to Reproduce the Bug

Using ooba try to change TRUNCATION_LENGTH

### Expected Behavior

TRUNCATION_LENGTH different from default 2048

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello, thank you for reporting this!  I just pushed an update to `main` to fix it.  I changed that while testing and forgot to change it back.
