### ISSUE TITLE
vscode path wrong /path/to/directory

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#779]
### Description

If you have the task chain and run chain running with a project to work on it will try to open in vscode like 

command code path/to/project etc...

and it won't open to the directory of which it needs to work on.

### Steps to Reproduce the Bug

1.Run task chain that requires a task that involves programming project stuff.

### Expected Behavior

Supposed to work inside the directory of cloned whatever project it cloned or locally working on with vscode to open in the correct path.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
That is AI hallucinating file paths.

**Comment by Josh-XT** [comment]
Same as #781
