### ISSUE TITLE
Task chain and Run not installing required dependencies for task 

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#780]
### Description

When you run a task chain it will try to run and not see what the output of the commands that its running so it doesn't know oh I need to install this etc... 

### Steps to Reproduce the Bug

1.Run task chain that involves a project which it needs dependencies to be able to work on whatever programming or software it needs to use to complete the task

### Expected Behavior

To be able to actually be aware of what its doing instead of just running through the task when it runs into things like 
npm: command not found etc... and many more and install the correct dependencies when completing the task.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
If the AI hasn't chosen to do this on its own with the prompt given, you'll need to mention to it that you don't have dependencies for your task in your prompt.
