### ISSUE TITLE
Task and chain not working on the project it says it is working on inside the working directory

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#781]
### Description

After that issue with it not going into the directory to create a directory that it needs to work on whatever project it says its working on /project/component/file.whatever  and it is really not doing anything or writing as its going through.

### Steps to Reproduce the Bug

1.Run a task chain that requires navigating though directories etc..

### Expected Behavior

To be able to work on the project and have a general sense of what its doing instead of saying oh I'm working on x thing but not doing x that inside of x directory when clearly its not and its just doing nothing.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Not all tasks will work with files, many may not.  If you're specifically needing the AI to look in a directory for things like code or files, you will need to tell it where that file is in your prompt, otherwise it will assume.
