### ISSUE TITLE
Add more support for working on different programming languages in tasks or instruct.

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#782]
### Feature/Improvement Description

I think adding more extensions to work on more tasks that require other programming languages would be great like a better management system for managing npm packages for node etc... also Ruby Gems etc.. managing for that and also Java maven or Gradle management to be able to work on projects that are written in Java.

### Proposed Solution

As mentioned above adding more extensions to support more programming languages like having a lot of functions to be able to work other languages better.

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
It should have full terminal access and the ability to read and write files, so it should be able to do all of those things. The LLMs know the languages, I just have Python specific things because one of the goals is self maintenance.
