### ISSUE TITLE
Task Chain stops like Smart Chain 

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#783]
### Description

This is a addition to #767 
Regular task chain also stops

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/40e0ddd1-a420-4bb0-be2a-1eb09a7300f0)

### Steps to Reproduce the Bug

1.Run Task chain

### Expected Behavior

No stop

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
It stopped the chain due to the error, there was no point in continuing if the expected result did not come.  It understands that an exception is not the expected result and stops.  The error you have has been fixed in #787 though.
