### ISSUE TITLE
Generate Smart Task Chain without Research failing

### ISSUE THREAD

**Issue by kkuette** [Josh-XT/AGiXT#793]
### Description

When using chain "Generate Smart Task Chain without Research" with override agent, the chain fail du to overrided agent not passed in the chain also the agent i'm using isnt allowed to use another agent.

```2023-06-24 22:30:27,353 | INFO | Executing command: Create Task Chain with args: {'command_name': 'Create Task Chain', 'agent': 'gpt4free', 'primary_objective': 'Write an api using fastpi.', 'numbered_list_of_tasks': ' Sure, I can help you break down the primary objective into a list of small achievable tasks. Here are some steps that could help you achieve your primary objective:\n\n1. Identify the primary objective: Please provide me with the primary objective so that I can begin breaking it down into smaller tasks.', 'short_chain_description': ' Fast API Integration', 'smart_chain': True, 'researching': False}. Command Function: <function agixt_chain.create_task_chain at 0x7f47d378e830>```

### Steps to Reproduce the Bug

Generate Smart Task Chain without Research using override agent

### Expected Behavior

it should keep the overrided agent or use another agent if allowed

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Command execution actually doesn't rely on agent, so it just ignores the flag for that part.

**Comment by Josh-XT** [comment]
https://github.com/Josh-XT/AGiXT/pull/794

Also I just did this a couple of minutes ago which will majorly improve task chain generation, give it a try.

**Comment by kkuette** [comment]
It seems to break when it post the new chain.
```2023-06-24 22:47:56,461 | INFO | Command Output: AI Generated Task -  "FastAPI: Store Code in Files" - 2023-06-24_22-47-56
2023-06-24 22:47:56,462 | INFO | Response: AI Generated Task -  "FastAPI: Store Code in Files" - 2023-06-24_22-47-56
INFO:     127.0.0.1:46084 - "POST /api/chain/Generate%20Task%20Chain%20without%20Research/run HTTP/1.1" 200 OK```

**Comment by Josh-XT** [comment]
> It seems to break when it post the new chain.
> 
> ```
> 2023-06-24 22:47:56,462 | INFO | Response: AI Generated Task -  "FastAPI: Store Code in Files" - 2023-06-24_22-47-56
> INFO:     127.0.0.1:46084 - "POST /api/chain/Generate%20Task%20Chain%20without%20Research/run HTTP/1.1" 200 OK```
> ```

Looks like it created the new chain, did it not?

**Comment by kkuette** [comment]
It didn't work, it's stuck.

**Comment by kkuette** [comment]
I've found the problem, i was just confused xD
