### ISSUE TITLE
Improve the tasks by implementing Camel Ai task structure

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#801]
### Feature/Improvement Description

Camel Ai has a awesome tasks process 

![image](https://github.com/Josh-XT/AGiXT/assets/34012548/892171be-6093-4e43-9908-22d1bd970421)
Image from their github 

### Proposed Solution

By utilizing role playing between an ai user and an ai helper the task can get finished really efficiently.

https://github.com/camel-ai/camel

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Added a new command `Ask for Help or Further Clarification to Complete Task` to help you accomplish this.  You will simply need to enable this command for your agent.

The Prompt:
```
{context}
My primary objective is: {user_input}.

My current task is: {task}.

I need assistance to complete the task.

{question}
```

The Command:
```python
    async def ask_for_help(
        self,
        agent: str,
        your_primary_objective: str,
        your_current_task: str,
        your_detailed_question: str,
    ) -> str:
        """
        Ask for Help or Further Clarification to Complete Task
        """
        return await ApiClient.prompt_agent(
            agent_name=agent,
            user_input=your_primary_objective,
            prompt_name="Ask for Help",
            prompt_args={
                "question": your_detailed_question,
                "task": your_current_task,
                "disable_memory": True,
            },
        )
```
