### ISSUE TITLE
NameError: name 'update_agent_settings_button' is not defined

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#813]
### Description

When I click Agent Settings, error appears

### Steps to Reproduce the Bug

Error loading agent configuration: 'str' object has no attribute 'get'

NameError: name 'update_agent_settings_button' is not defined
Traceback:
File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/mihai/AGiXT/streamlit/pages/0-Agent_Settings.py", line 236, in <module>
    if update_agent_settings_button:

### Expected Behavior

Error loading agent configuration: 'str' object has no attribute 'get'

NameError: name 'update_agent_settings_button' is not defined
Traceback:
File "/home/mihai/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/home/mihai/AGiXT/streamlit/pages/0-Agent_Settings.py", line 236, in <module>
    if update_agent_settings_button:

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please pull the latest changes and then run:

```
pip install agixt --upgrade
```

**Comment by mongolu** [comment]
deleted AGiXT folder, did git pull, then pip install agixtsdk --upgrade, run ./AGiXT.sh with option 1, but the same error appears

**Comment by mongolu** [comment]
Did the same now, the error is still present
