### ISSUE TITLE
add BlenderGPT for extension commands

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#824]
### Feature/Improvement Description

I think being able to integrate blendergpt would be great if anyone wanted to make something in blender with agixt

https://github.com/gd3kr/BlenderGPT

### Proposed Solution

adding blendergpt for an extension

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Only supports OpenAI and doesn't seem to be merging PRs to fix bugs.
