### ISSUE TITLE
OPENAI PROVIDER API Streaming Request Support

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#831]
### Feature/Improvement Description

Many apis use streaming so when you try to plug in an api it won't work as its only through a streaming request.

### Proposed Solution

Add Streaming request support for openai provider 

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
Modified to add a "stream" flag for it to handle providers streaming responses.

https://github.com/AGiXT/light-hub/blob/main/providers/openai.py
