### ISSUE TITLE
Process pages in parallel for Web Search

### ISSUE THREAD

**Issue by greengeckowizard** [Josh-XT/AGiXT#834]
### Feature/Improvement Description

Web Search is painfully slow as it process pages one by one.

### Proposed Solution

Processing pages in parallel will reduce the time it takes to process so many pages in web search.

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
This is in place now.  There is a 90 second wait to let it do all of the research it needs to do after it starts browsing pages.
