### ISSUE TITLE
Error Loading Agent Configuration: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by sambickeita** [Josh-XT/AGiXT#849]
### Description

When I attempt to load a local model, I encounter the error message 'str' object has no attribute 'get'. This error occurs during the process of loading the agent configuration, indicating a problem with accessing a specific attribute within the configuration.

### Steps to Reproduce the Bug

1. Agent Settings
2. Agent Name
3. wizardLM-13B.ggmlv3.q4_0
4. error : Error loading agent configuration: 'str' object has no attribute 'get'

agixt-main-agixt-1      | INFO:     Started server process [15]
agixt-main-agixt-1      | INFO:     Waiting for application startup.
agixt-main-agixt-1      | INFO:     Application startup complete.
agixt-main-agixt-1      | INFO:     Started server process [14]
agixt-main-agixt-1      | INFO:     Waiting for application startup.
agixt-main-agixt-1      | INFO:     Application startup complete.
agixt-main-agixt-1      | INFO:     Started server process [12]
agixt-main-agixt-1      | INFO:     Waiting for application startup.
agixt-main-agixt-1      | INFO:     Application startup complete.
agixt-main-agixt-1      | INFO:     Started server process [13]
agixt-main-agixt-1      | INFO:     Waiting for application startup.
agixt-main-agixt-1      | INFO:     Application startup complete.
agixt-main-agixt-1      | INFO:     172.19.0.3:58908 - "GET /api/agent HTTP/1.1" 200 OK
agixt-main-agixt-1      | INFO:     172.19.0.3:58912 - "GET /api/agent/wizardLM-13B-Uncensored.ggmlv3.q4_0 HTTP/1.1" 500 Internal Server Error
agixt-main-agixt-1      | ERROR:    Exception in ASGI application
agixt-main-agixt-1      | Traceback (most recent call last):
agixt-main-agixt-1      |   File "/agixt/Providers.py", line 36, in __init__
agixt-main-agixt-1      |     self.instance = provider_class(**kwargs)
agixt-main-agixt-1      |   File "/agixt/providers/openai.py", line 32, in __init__
agixt-main-agixt-1      |     self.stream = True if stream.lower() == "true" else False
agixt-main-agixt-1      | AttributeError: 'bool' object has no attribute 'lower'
agixt-main-agixt-1      | 
agixt-main-agixt-1      | The above exception was the direct cause of the following exception:
agixt-main-agixt-1      | 
agixt-main-agixt-1      | Traceback (most recent call last):
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
agixt-main-agixt-1      |     result = await app(  # type: ignore[func-returns-value]
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
agixt-main-agixt-1      |     return await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
agixt-main-agixt-1      |     await super().__call__(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
agixt-main-agixt-1      |     await self.middleware_stack(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
agixt-main-agixt-1      |     raise exc
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, _send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
agixt-main-agixt-1      |     raise exc
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, sender)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
agixt-main-agixt-1      |     raise e
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
agixt-main-agixt-1      |     await route.handle(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
agixt-main-agixt-1      |     await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
agixt-main-agixt-1      |     response = await func(request)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
agixt-main-agixt-1      |     raw_response = await run_endpoint_function(
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
agixt-main-agixt-1      |     return await dependant.call(**values)
agixt-main-agixt-1      |   File "/agixt/app.py", line 395, in get_agentconfig
agixt-main-agixt-1      |     agent_config = Agent(agent_name=agent_name).get_agent_config()
agixt-main-agixt-1      |   File "/agixt/fb/Agent.py", line 125, in __init__
agixt-main-agixt-1      |     self.PROVIDER = Providers(self.AI_PROVIDER, **self.PROVIDER_SETTINGS)
agixt-main-agixt-1      |   File "/agixt/Providers.py", line 42, in __init__
agixt-main-agixt-1      |     raise AttributeError(f"module {__name__} has no attribute {name}") from e
agixt-main-agixt-1      | AttributeError: module Providers has no attribute openai
agixt-main-agixt-1      | INFO:     172.19.0.3:43454 - "GET /api/agent HTTP/1.1" 200 OK
agixt-main-agixt-1      | INFO:     172.19.0.3:43470 - "GET /api/agent HTTP/1.1" 200 OK
agixt-main-agixt-1      | INFO:     172.19.0.3:43484 - "GET /api/agent/Llamacpp HTTP/1.1" 500 Internal Server Error
agixt-main-agixt-1      | ERROR:    Exception in ASGI application
agixt-main-agixt-1      | Traceback (most recent call last):
agixt-main-agixt-1      |   File "/agixt/Providers.py", line 36, in __init__
agixt-main-agixt-1      |     self.instance = provider_class(**kwargs)
agixt-main-agixt-1      |   File "/agixt/providers/openai.py", line 32, in __init__
agixt-main-agixt-1      |     self.stream = True if stream.lower() == "true" else False
agixt-main-agixt-1      | AttributeError: 'bool' object has no attribute 'lower'
agixt-main-agixt-1      | 
agixt-main-agixt-1      | The above exception was the direct cause of the following exception:
agixt-main-agixt-1      | 
agixt-main-agixt-1      | Traceback (most recent call last):
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
agixt-main-agixt-1      |     result = await app(  # type: ignore[func-returns-value]
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
agixt-main-agixt-1      |     return await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
agixt-main-agixt-1      |     await super().__call__(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
agixt-main-agixt-1      |     await self.middleware_stack(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
agixt-main-agixt-1      |     raise exc
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, _send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
agixt-main-agixt-1      |     raise exc
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, sender)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
agixt-main-agixt-1      |     raise e
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
agixt-main-agixt-1      |     await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
agixt-main-agixt-1      |     await route.handle(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
agixt-main-agixt-1      |     await self.app(scope, receive, send)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
agixt-main-agixt-1      |     response = await func(request)
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
agixt-main-agixt-1      |     raw_response = await run_endpoint_function(
agixt-main-agixt-1      |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
agixt-main-agixt-1      |     return await dependant.call(**values)
agixt-main-agixt-1      |   File "/agixt/app.py", line 395, in get_agentconfig
agixt-main-agixt-1      |     agent_config = Agent(agent_name=agent_name).get_agent_config()
agixt-main-agixt-1      |   File "/agixt/fb/Agent.py", line 125, in __init__
agixt-main-agixt-1      |     self.PROVIDER = Providers(self.AI_PROVIDER, **self.PROVIDER_SETTINGS)
agixt-main-agixt-1      |   File "/agixt/Providers.py", line 42, in __init__
agixt-main-agixt-1      |     raise AttributeError(f"module {__name__} has no attribute {name}") from e
agixt-main-agixt-1      | AttributeError: module Providers has no attribute openai

### Expected Behavior

Agent loaded

### Operating System

- [ ] Linux
- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by sambickeita** [comment]
Same error when I am loading starchat or gpt4free

Missing Submit Button

This form has no submit button, which means that user interactions will never be sent to your Streamlit app.

To create a submit button, use the st.form_submit_button() function.

For more information, refer to the [documentation for forms](https://docs.streamlit.io/library/api-reference/control-flow/st.form).

Error loading agent configuration: 'str' object has no attribute 'pop'

**Comment by mongolu** [comment]
`Error loading agent configuration: 'str' object has no attribute 'get'`

fresh git clone, with docker, in Agent Settings, choose any agent and the error is displayed.

**Comment by Josh-XT** [comment]
Updated OpenAI provider to fix this in both hubs.
