### ISSUE TITLE
Diff between nvidia yml files

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#852]
### Description

dockerfile: docker/Dockerfile is missing from postgres file

also this section too:
    environment:
      - CLI_ARGS=${CLI_ARGS}

### Steps to Reproduce the Bug

fresh git clone

### Expected Behavior

nvidia local and postgres to be in sync

I'm thinking that this is not smth to bother you with, but I'm not quite familiar with git in order to do it myself.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Fixed, thank you!
