### ISSUE TITLE
docker compose textgen deviceids

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#853]
### Feature/Improvement Description

[Here](https://docs.docker.com/compose/gpu-support/) I can see that if you don't specifi `device_ids `but `count: all`, then it will use all of your GPUs present in the system.
Now we have `device_ids: [ '0' ]` which I presume it specifies to use only the first GPU.

### Proposed Solution

replace `device_ids: [ '0' ]` with `count: all`

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
This appears resolved now.  Thank you!
