### ISSUE TITLE
Adding Petals as provider

### ISSUE THREAD

**Issue by UndefinedConstant** [Josh-XT/AGiXT#857]
### Feature/Improvement Description

Petals is a project for collaboratively running llm's with high parameter counts on consumer hardware and works similar to torrents and crypto mining pools where every user of the swarm hosts and processes a small part of the language model. 
It is a way of sharing ones gpu and cpu with the swarm in return for high inference speeds on big models when doing requests ourselves, and ofc the ability to run them "locally" in the first place

currently supported models LLaMA-2 70b and 70B-Chat, LLaMA-65B, Guanaco-65B and BLOOM-176B

https://github.com/bigscience-workshop/petals
https://github.com/petals-infra

### Proposed Solution

add petals as ai provider

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
https://github.com/AGiXT/hub/blob/main/providers/petals.py

Added, thanks!
