### ISSUE TITLE
command "google search" not show

### ISSUE THREAD

**Issue by ychy00001** [Josh-XT/AGiXT#859]
### Description

When I set GOOGLE_API_KEY , "google search" command not show in command setting list

### Steps to Reproduce the Bug

1. Click Agent Setting Page
2. Add new Agent "xxx"
3. set GOOGLE_API_KEY in Setting Page
4. find "google search" command

### Expected Behavior

"google search " in setting command list, can select

### Operating System

- [ ] Linux
- [ ] Microsoft Windows
- [X] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
I believe this should be fixed now, please let me know if ongoing.
