### ISSUE TITLE
.env file doesn't get to docker image even after COPY . .

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#867]
### Description

I've ckecked this with
`print(f"db_connected = {db_connected}")`
in Websearch.py
and it says False.
Checked after this in docker container and no .env file was present.

### Steps to Reproduce the Bug

run ./AGiXT.sh with option 3

### Expected Behavior

After running ./AGiXT.sh and .env file is created, this file should be propagated to docker image.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Should be fixed in #868 - let me know if still having issues.

**Comment by mongolu** [comment]
It throws this error:
`./launch-backend.sh: 9: .: .env: not found`

I've modified the Docker*.yml on the newly added volume to be like this:
`- ./.env:/.env`

Now it works, from this point of view.

**Comment by mongolu** [comment]
I've got past this, modified the 2 file with gpt4all to pass, run Hub.py successfully.
Now when i go in the webpage for Agents, make modifications, push the button for update settings, when refresh agents (choose another one and then choose again the modified one), no changes are persisted, all settings are the same as before modifications.
I presume something is not doing what it should on the db side.

**Comment by Josh-XT** [comment]
Updated to `- ./.env:/.env` to resolve issue.
