### ISSUE TITLE
ModuleNotFoundError: No module named 'nomic.gpt4all'

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#876]
### Description

Posting new issue because the problem is still there

### Steps to Reproduce the Bug

Posting new issue because the problem is still there

### Expected Behavior

Posting new issue because the problem is still there

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by CaullenOmdahl** [comment]
Also having the same issue in the same environment. Ubuntu 22.04

**Comment by Josh-XT** [comment]
All fixed up, just needed to change package name.  Something must have changed in one of the previous versions.
