### ISSUE TITLE
Installation problems, and many other problems, it was not possible to get the software package to work

### ISSUE THREAD

**Issue by pegas07770** [Josh-XT/AGiXT#901]
System:
   Host: Kernel: 6.4.0-2-rt6-MANJARO arch: x86_64 bits: 64
     Desktop: Xfce v: 4.18.1 Distro: Manjaro Linux
 Machine:
   Type: Desktop: ASUSTeK model: P8H61-M LX2 R2.0 v: Rev X.0x
 CPU:
   Info: quad core model: Intel Core i5-3470 
 Graphics:
   Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 535.86.05
   Display: x11 server: X.Org v: 21.1.8 driver: X: loaded: nvidia gpu: nvidia
     s-res: 1280x1024
 Memory: DDR3 total: 12 GiB 
 ID-1: swap-1 type: partition size: 30 GiB used: 0 KiB (0.0%) dev: /dev/sde6 SSD
 There are a lot of problems, nothing works as intended by respected authors, developers.  I will write bug reports gradually, step by step.  A very interesting solution, but unfortunately nothing works for me, thank you very much for your work, dear developers, but I would like to correct errors.
 Let's start with the fact that installing with AGiXT.sh causes an error

 Visit our documentation at https://AGiXT.com 
 Welcome to the AGiXT Installer!
 Please choose an option:
   1. Run AGiXT with Docker (Recommended)
   2. Run AGiXT Locally (Developers Only - Not Recommended or Supported) 
   3. Run AGiXT and Text generation web UI with Docker (NVIDIA Only)
   4. Update AGiXT 
   5. Wipe AGiXT Hub (Irreversible)
   6.Exit
Enter your choice: 3
 /home/agi/AGiXT/AGiXT.sh: line 193: dpkg: command not found
 NVIDIA Container Toolkit is not installed.  Installing now...
 [sudo] agi password: 
 sudo: apt-key: command not found
 tee: /etc/apt/sources.list.d/nvidia-docker.list: No such file or directory
 # Unsupported distribution!
 # Check https://nvidia.github.io/nvidia-docker
 sudo: apt-get: command not found
 NVIDIA Container Toolkit has been installed.

I asked ChatGPT to fix the AGiXT.sh script for my systems and only then did it work.  AGiXT.sh script fixes : Original code snippet:  
 # Check if nvidia-container-toolkit is installed
  if dpkg -l | grep -iq "nvidia-container-toolkit"; then
      echo "Confirmed NVIDIA Container Toolkit is installed."
  else
      echo "NVIDIA Container Toolkit is not installed. Installing now..."
      # Install a new GPU Docker container
      distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
      curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
      curl -s -L https://nvidia.github.io/nvidia-docker/$distributInstallation problems, and many other problems, it was not possible to get the software package to workion/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
      sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
      sudo systemctl restart docker
      echo "NVIDIA Container Toolkit has been installed."
  fi

  if [[ "$AGIXT_AUTO_UPDATE" == "true" ]]; then
    update
  fi

The corrected piece of code for Manjaro linux allows you to install AGiXT normally, without problems:

  # Check if nvidia-container-toolkit is installed
  if pacman -Q nvidia-container-toolkit > /dev/null 2>&1; then
    echo "Confirmed NVIDIA Container Toolkit is installed."
else
    echo "NVIDIA Container Toolkit is not installed. Installing now..."
    # Install NVIDIA Container Toolkit
    yay -S nvidia-container-toolkit
    sudo systemctl restart docker
    echo "NVIDIA Container Toolkit has been installed."
fi

  if [[ "$AGIXT_AUTO_UPDATE" == "true" ]]; then
    update
  fi

  if [[ "$AGIXT_AUTO_UPDATE" == "true" ]]; then
    update
  fi

 I note that nothing worked on Ubuntu 20.04 LTS either, the installation went without problems, but the agents were not created and did not work at all.  Is it possible to send error reports directly from your software package?  I did not find such a function there.

### Steps to Reproduce the Bug

Installing [user@host AGiXT]$ ./AGiXT.sh

### Expected Behavior

Installation and operation of the software package without errors in accordance with the description of the project.  I hope that this will happen.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Ah interesting! Manjaro.  I am not real familiar with that distro unfortunately.   The installer is mostly set up to work with Debian flavors mostly.  I haven't had any issues getting it running in Ubuntu.

No need to fear though!  The functionality of the installer can be easily replaced by editing one file and running docker-compose directly.

Set your `.env` file content to:
```
DB_CONNECTED=false
AGIXT_AUTO_UPDATE=true
AGIXT_HUB=AGiXT/hub
AGIXT_API_KEY=
UVICORN_WORKERS=10
GITHUB_USER=
GITHUB_TOKEN=
POSTGRES_SERVER=db
POSTGRES_PORT=5432
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
TORCH_CUDA_ARCH_LIST=7.5
CLI_ARGS="--listen --api --chat"
AGIXT_URI=http://localhost:7437
TEXTGEN_URI=http://localhost:5000
```

Then just go to the AGiXT folder and run:
```
docker-compose up
```
