### ISSUE TITLE
 Agents working with models running in Google Colab using Oobabooga Web UI?

### ISSUE THREAD

**Issue by pegas07770** [Josh-XT/AGiXT#902]
### Feature/Improvement Description

Would you like to be able to use your project to work with local language models launched by Google Coolab using Oobabooga Web UI?  Here is an example of such notebooks that allow you to run LLM in Google Coolab using Oobabooga Web UI https://github.com/Troyanovsky/Local-LLM-Comparison-Colab-UI
 Maybe you can use this as an LLM provider running on a remote server?

### Proposed Solution

I don't know how it can be done or if it can be done at all.  This is just a suggestion, an idea to improve the project.

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by Josh-XT** [comment]
You could use any of those notebooks with AGiXT if the url is externally accessible. Just use that as your Ooba provider url.
