### ISSUE TITLE
NameError: name 'all_responses' is not defined

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#903]
### Description

Instruct, Chains, Smart Instruct

```
agixt-agixt-1                    | INFO:     172.18.0.5:52316 - "GET /api/chain/Smart%20Instruct/args HTTP/1.1" 200 OK
agixt-streamlit-1                | 2023-08-12 15:47:00.417 Uncaught app exception
agixt-streamlit-1                | Traceback (most recent call last):
agixt-streamlit-1                |   File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
agixt-streamlit-1                |     exec(code, module.__dict__)
agixt-streamlit-1                |   File "/app/pages/0-Agent Interactions.py", line 99, in <module>
agixt-streamlit-1                |     all_responses=all_responses,
agixt-streamlit-1                | NameError: name 'all_responses' is not defined

```

### Steps to Reproduce the Bug

ver 1.3.93

### Expected Behavior

If i go first to Learing and learn some file, after that it works

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
Correction, it doesn't work.
But, if I check "Show Advanced Option" and just this, no altering of defaults, after this it works.

**Comment by Josh-XT** [comment]
This has been resolved
