### ISSUE TITLE
/root/.cache/chroma/onnx_models/all-MiniLM-L6-v2/onnx.tar.gz: very slow download

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#904]
### Description

When doing first time a Learning, the all-MiniLM-L6-v2 is downloading, but is very veeeery slow: 80kiB/s

### Steps to Reproduce the Bug

Can smth be done here?

### Expected Behavior

Do a learning from file first time after a fresh docker start (option 3).
(i purged containers first)

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
The file it downloads is 80mb, it downloaded in about 20 seconds for me.  How large of a file are you getting?

**Comment by Josh-XT** [comment]
I just added the model to the repo, waiting on the build to finish but that should hopefully resolve this issue.

**Comment by mongolu** [comment]
This would be nice.

I've retried now v.1.3.95 (after deleting container and images and rebuild them) with website learning at it throws:
```
agixt-agixt-1                    |   File "/agixt/Embedding.py", line 31, in get_embedder
agixt-agixt-1                    |     embed = embedding_functions.ONNXMiniLM_L6_V2(DOWNLOAD_PATH=os.getcwd())
agixt-agixt-1                    | TypeError: ONNXMiniLM_L6_V2.__init__() got an unexpected keyword argument 'DOWNLOAD_PATH'
```
It's the same for GitHub Repository.

For file learning it only throws:
`agixt-agixt-1                    | INFO:     172.18.0.5:47078 - "POST /api/agent/Starchat/learn/file HTTP/1.1" 500 Internal Server Error
`

**Comment by Josh-XT** [comment]
I should have that error fixed in the latest AGiXT build once it finishes.

I also put it in a pull request with Chroma that will help.  We need to have the tar.gz and extracted onnx folder in the repo for it to work properly currently, having one or the other wasn't working.  https://github.com/chroma-core/chroma/pull/976

**Comment by mongolu** [comment]
Thank you, it's ok now.
