### ISSUE TITLE
Errors when trying to load any ggmlv3 model into agixt-text-generation-webui with any settings and loaders.

### ISSUE THREAD

**Issue by pegas07770** [Josh-XT/AGiXT#906]
### Description
Any ggmlv3 variants of the LLM models don't work for me in agixt-text-generation-webui, which are designed and should work in oobabooga /text-generation-webui.   It seems that the problem is incompatibility of software and computer hardware, from what I managed to find out on google.
 I am ready to create any reports with technical information for the respected Developer Josh-XT.  I am ready to provide all possible assistance to the respected Developer Josh-XT to find the causes of problems and fix them.  I am ready to give Josh-XT remote access to my machine at any time convenient for Josh-XT and for any required period of time.

System:
Distro: Manjaro Linux Desktop: Xfce v: 4.18.1 
Host: Kernel: 6.4.0-2-rt6-MANJARO arch: x86_64 bits: 64
Machine:
Type: Desktop: ASUSTeK model: P8H61-M LX2 R2.0 v: Rev X.0x
CPU: quad core model: Intel Core i5-3470
Graphics: Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 535.86.05
Display: x11 server: X.Org v: 21.1.8 driver: X: loaded: nvidia gpu: nvidia
s-res: 1280x1024
Memory: DDR3 total: 12 GiB
ID-1: swap-1 type: partition size: 30 GiB used: 0 KiB (0.0%) dev: /dev/sde6 SSD

In any case, I express my gratitude to you, dear Josh-XT, for your work!  I see the potential of your project and it seems to me very interesting and important, I have long dreamed of seeing the implementation of something like this, and finally I found a Guy who took the matter seriously!  But I am very sorry that this does not work completely for me and I cannot touch this new, in my opinion, unique project, see how it works with my own eyes.  With best regards, I shake your hand, Dear Josh-XT!
   
   

### Steps to Reproduce the Bug

When trying to load any ggmlv3 model in agixt-text-generation-webui, the view of the llama.cpp loader, with different settings:
agixt-text-generation-webui-1  | Starting API at http://0.0.0.0:5000/api
agixt-text-generation-webui-1  | Running on local URL:  http://0.0.0.0:7860
agixt-text-generation-webui-1  | 
agixt-text-generation-webui-1  | To create a public link, set `share=True` in `launch()`.
agixt-text-generation-webui-1  | 2023-08-13 02:36:41 INFO:Loading stablebeluga-7b.ggmlv3.q4_0.bin...
agixt-text-generation-webui-1  | Illegal instruction (core dumped)
agixt-text-generation-webui-1 exited with code 132
After this error, the agixt-text-generation-webui docker container crashes completely out.  And it can only be restarted. 
These model files work fine in koboldcpp-1-41-1, meaning they are fine on their own.
I suspect that this problem appeared after another update of oobabooga / text-generation-webui before using AGiXT and this is somehow related to my system, processor instructions, for example AVX2 which are not supported by older CPUs, and possibly with a GTX 1050TI video card.  Then I had to switch to koboldcpp-1-41-1, but since AGiXT is integrated with oobabooga text-generation-webui I would like to deal with this problem.

### Expected Behavior

The operation of the AGiXT software package without errors in accordance with the description of the project.  I hope this happens.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [X] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello @pegas07770 .

There is a Kobold provider if you would like to just use that.  I just offer a direct integration with Oobabooga because it is fairly easy to set up.  I am not sure what any of the required drivers or packages would be for your card personally and I cannot support their software because I am just not familiar enough with it. 

https://github.com/oobabooga/text-generation-webui

I would recommend taking a look at their documentation in their repository to see if you can hunt down the culprit for this issue.  I would try going to the ooba webui directly to see if you can generate text in there before trying with AGiXT. That will confirm if your model settings are set up properly on the ooba side at least.
