### ISSUE TITLE
Suggestion for improving the installer/loader script AGiXT.sh

### ISSUE THREAD

**Issue by pegas07770** [Josh-XT/AGiXT#907]
### Feature/Improvement Description

ChatGPT, how can I change this code so that it is compatible and works on all Linux architectures?  Including my manjaro system? AGiXT.sh file

   ```
# Check if nvidia-container-toolkit is installed
  if dpkg -l | grep -iq "nvidia-container-toolkit"; then
      echo "Confirmed NVIDIA Container Toolkit is installed."
  else
      echo "NVIDIA Container Toolkit is not installed. Installing now..."
      # Install a new GPU Docker container
      distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
      curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
      curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
      sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
      sudo systemctl restart docker
      echo "NVIDIA Container Toolkit has been installed."
  fi
```

### Proposed Solution

****This code requires Josh-XT verification.  I AM NOT RESPONSIBLE FOR YOU RUNNING THIS CODE, THIS IS ONLY FOR Josh-XT !  Everything works for me on Manjaro Linux.*****

ChatGPT: 
The code you provided is written for Debian-based Linux distributions and uses the "dpkg" package manager to check if the "nvidia-container-toolkit" is installed. Since Manjaro is an Arch-based distribution, the "dpkg" package manager is not available. To make this code compatible with Manjaro and other Arch-based distributions, you can replace the "dpkg" command with the "pacman" command, which is the package manager used by Arch-based distributions. Here's the updated code:
```
# Check if nvidia-container-toolkit is installed
if pacman -Qs nvidia-container-toolkit > /dev/null ; then
    echo "Confirmed NVIDIA Container Toolkit is installed."
else
    echo "NVIDIA Container Toolkit is not installed. Installing now..."
    # Install a new GPU Docker container
    distribution=$(awk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"')
    curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo
    sudo yum install -y nvidia-container-toolkit
    sudo systemctl restart docker
    echo "NVIDIA Container Toolkit has been installed."
fi
```

In this updated code, the "pacman" command is used to check if the "nvidia-container-toolkit" package is installed. The "awk" command is used to extract the name of the Linux distribution from the "/etc/os-release" file, which is then used to construct the URL for the NVIDIA Docker repository. The "yum" package manager is used to install the "nvidia-container-toolkit" package, which is then followed by restarting the Docker service. This code should work on Manjaro and other Arch-based distributions.

pegas07770: But will it still be compatible and work on the original systems for which it was written?

ChatGPT: 
The updated code that I provided in my previous answer is specifically designed to work on Arch-based distributions like Manjaro. However, it may not work on Debian-based distributions or other Linux distributions that use a different package manager or have a different package name for the NVIDIA Container Toolkit. If you want to make the code compatible with both Debian-based and Arch-based distributions, you can use a conditional statement to check the Linux distribution and use the appropriate package manager and package name for the NVIDIA Container Toolkit. Here's an example of how you can modify the code to make it compatible with both Debian-based and Arch-based distributions:

```
# Check if nvidia-container-toolkit is installed
if command -v dpkg > /dev/null && dpkg -l | grep -iq "nvidia-container-toolkit"; then
    echo "Confirmed NVIDIA Container Toolkit is installed."
elif command -v pacman > /dev/null && pacman -Qs nvidia-container-toolkit > /dev/null ; then
    echo "Confirmed NVIDIA Container Toolkit is installed."
else
    echo "NVIDIA Container Toolkit is not installed. Installing now..."
    # Install a new GPU Docker container
    if command -v dpkg > /dev/null; then
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
        sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
        sudo systemctl restart docker
    elif command -v pacman > /dev/null; then
        distribution=$(awk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"')
        curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo
        sudo yum install -y nvidia-container-toolkit
        sudo systemctl restart docker
    else
        echo "Unsupported Linux distribution. Please install NVIDIA Container Toolkit manually."
        exit 1
    fi
    echo "NVIDIA Container Toolkit has been installed."
fi
```

In this updated code, the "command -v" command is used to check if the "dpkg" or "pacman" command is available. If the "dpkg" command is available, the code assumes that the Linux distribution is Debian-based and uses the "apt-get" package manager to install the "nvidia-container-toolkit" package. If the "pacman" command is available, the code assumes that the Linux distribution is Arch-based and uses the "yum" package manager to install the "nvidia-container-toolkit" package. If neither command is available, the code prints an error message and exits. This code should work on both Debian-based and Arch-based distributions, as well as other Linux distributions that use either "apt-get" or "yum" as their package manager.

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by pegas07770** [comment]
Hello, dear [Josh-XT](https://github.com/Josh-XT), don’t think that I’m lazy.  Could you send me the corrected AGiXT.sh file here?  With the changes already made that you suggested.  I just don’t understand where to edit, there are 2 (two) places with this code.  Sorry, but I'm not even a programmer.  I'm just a very advanced user.  ChatGPT writes the code for me.  Unfortunately, I can’t write even the simplest script myself.  Please send me in attachments or a link to any open file hosting service (for example https://www.file.io/) the file AGiXT.sh corrected for me. And I will check it on Manjaro linux and send you an error report (if there are any errors) .  This will be the right approach.  So that I don’t interfere with your project with my crooked hands.  With respect to you @[pegas07770](https://github.com/pegas07770) pegas07770

**Comment by Josh-XT** [comment]
Option 1 is most ideal for most people.  It uses `docker-compose` instead of installing anything on the local filesystem.

**Comment by pegas07770** [comment]
> Вариант 1 наиболее идеален для большинства людей. Оно использует `docker-compose`вместо установки чего-либо в локальную файловую систему.
[Josh-XT](https://github.com/Josh-XT)
Yes, but this does not change the fact that 2. Run AGiXT with Text Generation Web UI (NVIDIA Only) your project cannot be used on the arch linux family (I have manjaro linux) without changing the AGiXT.sh code

**Comment by pegas07770** [comment]
[Josh-XT](https://github.com/Josh-XT) https://huggingface.co/models?sort=trending&search=+Mistral-7B-v0.1+ did you see this?  This is a breakthrough!  The 7 billion parameters model outperformed LLAMA 2 13b!!!  8 thousand context tokens!  At this rate, by the end of next year we will have free standalone AGI-level models freely available.  I want to notice local models!  Your project is very important to me!  I will now write bug reports; local models with koboldcpp do not work fine for me.  Generate off-topic responses in AGiXT.  Something is wrong, I suspect your instructions are in the wrong format.  Maybe I'm wrong.  But in the koboldcpp and SillyTavern-1.10.4 web interfaces the models work perfectly.  Please test on your computer how the latest GGUF format models work in koboldcpp-1.44.2.  I beg you very much.  I use Select Provider kobold Select Helper Agent gpt4free Any models generate responses in Agent Interactions that do not correspond to requests, in any modes, chat, promt, instruction.  Please check it for yourself!
