### ISSUE TITLE
 libnvidia-ml.so.1: cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by eXactPlay** [Josh-XT/AGiXT#913]
### Description

This appears when I try to launch on RHEL 8, Nvidia docker 2 installed.

```
ERROR: for text-generation-webui  Cannot start service text-generation-webui: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

### Steps to Reproduce the Bug

1. Run the script
2. Select text-generation-webui
3. Wait for updates to run
4. Observe the error

### Expected Behavior

Script runs text-generation-webui successfully.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
I would recommend making this issue on ooba's repo.  We're just using their docker-compose file to launch it.  That looks like your computer might be missing an expected driver or the ENV settings are pointing to the wrong versions.

**Comment by eXactPlay** [comment]
Thank you, did that now.
