### ISSUE TITLE
Running chains not working

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#916]
### Description

When I run the chain "Write a poem" it's working, small portion of the log:
```
agixt-agixt-1                    | INFO:     172.18.0.2:56096 - "GET /api/Starchat/conversations HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:56108 - "GET /api/conversation HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:56124 - "GET /api/chain HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:56138 - "GET /api/agent HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:56150 - "GET /api/chain HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:56154 - "GET /api/chain/Write%20a%20Poem/args HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     127.0.0.1:41934 - "GET /api/chain/Write%20a%20Poem HTTP/1.1" 200 OK
agixt-agixt-1                    | 2023-08-14 09:01:13,682 | INFO | Running chain 'Write a Poem'
agixt-agixt-1                    | 2023-08-14 09:01:13,682 | INFO | Running step 1 with agent Starchat.
agixt-agixt-1                    | INFO:     127.0.0.1:41950 - "GET /api/agent/Starchat HTTP/1.1" 200 OK
agixt-agixt-1                    | 2023-08-14 09:01:15,123 | INFO | CONTEXT RESULTS: 5
agixt-agixt-1                    |   A sunset over the ocean
agixt-agixt-1                    |   A lost love found again
....
```

But when tring to run other chains (tried Smart Instruct, Generate Task Chain), it hangs:
```
agixt-agixt-1                    | INFO:     172.18.0.2:37896 - "GET /api/Starchat/conversations HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:37906 - "GET /api/conversation HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:37918 - "GET /api/chain HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:37928 - "GET /api/agent HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:37934 - "GET /api/chain HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.18.0.2:37946 - "GET /api/chain/Smart%20Instruct/args HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     127.0.0.1:36180 - "GET /api/chain/Smart%20Instruct HTTP/1.1" 200 OK
agixt-agixt-1                    | 2023-08-14 08:59:13,482 | INFO | Running chain 'Smart Instruct'
agixt-agixt-1                    | 2023-08-14 08:59:13,482 | INFO | Running step 1 with agent Starchat.
agixt-agixt-1                    | INFO:     127.0.0.1:36202 - "GET /api/agent/Starchat HTTP/1.1" 200 OK

```

No other error, just hangs.

### Steps to Reproduce the Bug

1. Agent Interactions
2. Chains
3. Starchat
4. Smart Instruct
5. write some text in user input : "tell me a joke with pirates"
6. Run Chain

### Expected Behavior

I leave it run more than 20 minutes, no new entry log.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by mongolu** [comment]
I this behaviour is because Override agent isn't functioning.
(by default chain comes with gpt4free, but at runtime i change with starchat).

I say this because went on in Chain Management, modified default agent in Starchat, went back to Agent Interactions and now the chain started when press Start Chain.

**Comment by Josh-XT** [comment]
Is the override agent working now for you?

**Comment by mongolu** [comment]
No, it doesn't.
It's just saying:
```
agixt-agixt-1                    | INFO:     172.21.0.5:50816 - "GET /api/chain HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     172.21.0.5:50830 - "GET /api/chain/Smart%20Instruct/args HTTP/1.1" 200 OK
agixt-agixt-1                    | INFO:     127.0.0.1:59716 - "GET /api/chain/Smart%20Instruct HTTP/1.1" 200 OK
agixt-agixt-1                    | 2023-08-16 06:32:57,688 | INFO | Running chain 'Smart Instruct'
agixt-agixt-1                    | 2023-08-16 06:32:57,688 | INFO | Running step 1 with agent Starchat.
agixt-agixt-1                    | INFO:     127.0.0.1:59724 - "GET /api/agent/Starchat HTTP/1.1" 200 OK

```
And after this , nothing.
v1.3.109

**Comment by mongolu** [comment]
I've deleted the containers and also the docker images, rebuild them but something is strange because I don't understand why it's happening.

I've put some url in Agent Management -> SEARXNG_INSTANCE_URL and after install I expected to be empty but it is there. Also, all the other settings I've modified for the agent.

**Comment by mongolu** [comment]
It is working now (v1.3.11), thanks.
