### ISSUE TITLE
Agent Management - OpenAI overrides local configured provider

### ISSUE THREAD

**Issue by m4t7** [Josh-XT/AGiXT#928]
### Description

New Agent Provider setting is not saved. I suspect it is the new error handler. 
In the console log I get only 200 OKs for all transactions.

I followed the instructions for GPT4all. https://josh-xt.github.io/AGiXT/3-Providers/GPT4ALL.html

![image](https://github.com/Josh-XT/AGiXT/assets/12598384/a1a4d073-9d84-433e-bc66-6f75aaf15a43)
![image](https://github.com/Josh-XT/AGiXT/assets/12598384/4c8bea9d-3624-423d-b0ec-09bfd195eed0)

Here is a export from an  saved GPT4all  Agent, it contains not the correct data.
```
{
    "commands": null,
    "settings": {
        "provider": "openai",
        "embedder": "openai",
        "AI_MODEL": "gpt-3.5-turbo-16k-0613",
        "AI_TEMPERATURE": "0.7",
        "AI_TOP_P": "1",
        "MAX_TOKENS": "16000",
        "helper_agent_name": "OpenAI",
        "WEBSEARCH_TIMEOUT": 0,
        "OPENAI_API_KEY": "YOUR_OPENAI_API_KEY_HERE",
        "WAIT_BETWEEN_REQUESTS": 1,
        "WAIT_AFTER_FAILURE": 3,
        "stream": false,
        "WORKING_DIRECTORY": "./WORKSPACE",
        "WORKING_DIRECTORY_RESTRICTED": true,
        "AUTONOMOUS_EXECUTION": false
    },
    "enabled_commands": []
}
```

### Steps to Reproduce the Bug

1. Deploy a new setup via docker-compose method in AGiXT.sh script.
2. Go to Agent Management 
3. Create new Agent 
4. Select a provider like "gpt4all"
5. set Provider specific settings 
6. go to bottom and save
7. export settings or go to Agent Interaction and back to Agent Management select the newly created custom Agent or Test the new agent , the console will show that OpenAI was tried.

### Expected Behavior

Saved Provider Settings. 

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [ ] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
I just updated the defaults in v1.3.108 to fix these defaults.

**Comment by Josh-XT** [comment]
I see what the issue is now.  The way that Gpt4all is initialized has apparently changed and it is erroring.  I would recommend a different provider for now, I'll move gpt4all to dev branch for fixing and out of main repo.
