### ISSUE TITLE
docker error mounting /.env

### ISSUE THREAD

**Issue by mongolu** [Josh-XT/AGiXT#942]
### Description

I don't know why, but when running ./AGiXT option 2, it throws this error:
```
Attaching to agixt-agixt-1, agixt-streamlit-1, agixt-text-generation-webui-1
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/5b877f8d1e77b98e0ae8a8f2b6c61dfb30e363302a63a99d31483f9b855ac5b4" to rootfs at "/.env": mount /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/5b877f8d1e77b98e0ae8a8f2b6c61dfb30e363302a63a99d31483f9b855ac5b4:/.env (via /proc/self/fd/9), flags: 0x5000: no such file or directory: unknown
```

If I delete the container , then it works.

### Steps to Reproduce the Bug

running ./AGiXT option 2

### Expected Behavior

.

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
You may have to recursively `chown` everything in your AGiXT directory. That appears to be a potential permissions issue.
