### ISSUE TITLE
Local ChatGPT server connection randomly timing out

### ISSUE THREAD

**Issue by DadamaldaDad** [Josh-XT/AGiXT#964]
### Description

When i try to access my local OpenAI compatible API using my local ip and the port, sometimes the connection stops working and i have to restart the AGiXT backend to make it work again.
The API i'm using is RWKV Runner (the RWKV World model didn't work with oobabooga) which i noticed does not list the embedder in the models endpoint but supports embeddings.
The API does not know about the HTTP request and the backend just says connection timed out.

### Steps to Reproduce the Bug

1. Locally run an OpenAI compatible API (Preferably RWKV Runner)
2. Setup the agent
3. Create a conversation
4. Click "Send" in chat mode about 3-5 times and wait for response

### Expected Behavior

After clicking "Send", the connection should not repeatedly time out and the backend should connect to the API.

### Operating System

- [ ] Linux
- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [x] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Try adding a wait between requests in your agent settings, this is generally due to the provider's rate limits.

**Comment by DadamaldaDad** [comment]
Doesn't work. I had even worse issues using langchain. It's either not asking the server or there is a server issue.

**Comment by DadamaldaDad** [comment]
Problem solved. I just had to switch the provider to custom and it works flawlessly.
