### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by nikitaminiaev** [Josh-XT/AGiXT#994]
### Description

such errors, as well as with all other variables:
ERROR: Invalid interpretation format for "db" option in service "services": "${POSTGRES_DB:-postgres}"

### Steps to Reproduce the Bug

~ ./AGiXT.sh

~ Please choose an option:
  1. Run AGiXT (Recommended)
  
~  Update complete.
Starting Docker Compose...
ERROR: Invalid interpolation format for "db" option in service "services": "${POSTGRES_DB:-postgres}"
 

### Expected Behavior

I do not know, I am launching for the first time

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [X] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Please delete your `.env` file then when you run the installer again, choose to quick start and option 1 to start it. Using the database option is not necessary.

**Comment by nikitaminiaev** [comment]
is it possible to run local llama models in the quick start option? I was setting it up .env for the sake of it

**Comment by nikitaminiaev** [comment]
deleted .in, choose quick start:

ERROR: Invalid interpolation format for "agixt" option in service "services": "UVICORN_WORKERS=${UVICORN_WORKERS:-10}"
Update Completed...
Update complete.
Starting Docker Compose...
ERROR: Invalid interpolation format for "agixt" option in service "services": "UVICORN_WORKERS=${UVICORN_WORKERS:-10}"

**Comment by Josh-XT** [comment]
You may need to reboot, seems like docker can't start the services.

**Comment by nikitaminiaev** [comment]
if I replace everywhere  
`${UVICORN_WORKERS:-10} ` with
`$${UVICORN_WORKERS:-10}`

Then the following error occurs

```
Please wait...
Current directory: /home/nekit/PycharmProjects/llm/AGiXT
ERROR: Invalid interpolation format for "agixt" option in service "services": "AGIXT_HUB=${AGIXT_HUB:-AGiXT/hub}"
Updates Completed...
Update complete.
Starting Docker Compose...
ERROR: Invalid interpolation format for "agixt" option in service "services": "AGIXT_HUB=${AGIXT_HUB:-AGiXT/hub}"
```

**Comment by nikitaminiaev** [comment]
it doesn't work in any way

**Comment by Josh-XT** [comment]
Have you tried rebooting or resetting your docker service? I've had errors similar out of docker on my laptop and had to reboot to get docker working.

**Comment by nikitaminiaev** [comment]
```
sudo systemctl restart docker
sudo systemctl restart docker
```
it didn't help.
I removed all the problematic default values that he was swearing at for example:
```
NEXT_PUBLIC_API_URL=${AGIXT_URI:-http://agixt:7437}
->
NEXT_PUBLIC_API_URL=${AGIXT_URI}
```
an error occurs:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'nextjs'
Updates Completed...
Update complete.
Starting Docker Compose...
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'streamlit'

```

**Comment by nikitaminiaev** [comment]
when I added the version everything worked
```
version: '2.2'
```

**Comment by Josh-XT** [comment]
> when I added the version in docker-compose.yml everything worked
> 
> ```
> version: '2.2'
> ```

Interesting! I don't have a version defined in any of my docker-compose files apparently.  What version of docker and docker-compose are you running?  You may want to update them.

**Comment by nikitaminiaev** [comment]
```
docker-compose version 1.24.1, build 4667896b
Docker version 24.0.6, build ed223bc
```
probably need to update

**Comment by nikitaminiaev** [comment]
but it is also desirable for you to specify version in docker-compose.ym

**Comment by Josh-XT** [comment]
Your docker version is good but compose is outdated.  I agree that it would be a good idea to add the version, especially if it is causing issues.  Docker's documentation lists it as optional.  I'll update the compose files to use 3.7 like another project I'm working on uses.
